### ISSUE TITLE
Explanation of Permissions

### ISSUE THREAD

**Issue by yaomtc** [dslul/openboard#10]
An explanation of permissions would be a useful thing to add to the README. Especially these:

- view network connections
  Allows the app to view information about network connections such as which networks exist and are connected.
- android.permission.DOWNLOAD_WITHOUT_NOTIFICATION

I'm guessing this is used for the downloading of additional dictionaries?

**Comment by jwsp1** [comment]
Please consider removing all network access permissions. It will make your app more trustworthy. In order to download new languages, downloading separate apps for each supported language would be an alternative. 
Nearly all privacy keyboard work that way. You might want to check out their source code 👀

**Comment by dslul** [comment]
You're absolutely right, they were there in AOSP and I forgot to remove them. I commited [this change](https://github.com/dslul/openboard/commit/f19e7dfe1412cf69790cfc03615ab2c3ede7a774).

**Comment by dkanada** [comment]
I would remove the sync permissions too unless you're using them. I was also under the impression that apps don't actually need to request network permission to send and receive data, which is unfortunately what most people would be worried about, but that can't be helped.

**Comment by dslul** [comment]
The update without the permissions should be live after the next f-droid build batch (it's already available on the play store).

**Comment by dpintof** [comment]
I think you should also either remove or explain (in the README.md) the permissions related with the following:
* Sync;
* User accounts;
* Contacts.

Thanks

**Comment by dslul** [comment]
> I think you should also either remove or explain (in the README.md) the permissions related with the following:
> 
>     * Sync;
> 
>     * User accounts;
> 
>     * Contacts.
> 
> 
> Thanks

Removed in 3263ae00ccca60085cc1f28e22b8a08bfe9eb64d together with a lot of code that used to handle dictionary updates and google account connection in aosp. I'll test if this broke something, but everything seems to work as before.
Contacts are used to add your contact list to suggestions, it is disabled by default (and I personally keep it that way), but I don't think I'll remove it.

**Comment by yaomtc** [comment]
Great, thanks! The other permission is Storage, specifically `android.permission.WRITE_EXTERNAL_STORAGE`. I can't find anything that actually causes the permission prompt to appear, though. Is this connected to the download capability that you recently removed?

**Comment by dpintof** [comment]
Please don't forger to push the new versions to F-Droid. I'm waiting for the version with less permissions (it's still on V1.0)

**Comment by dslul** [comment]
> Please don't forger to push the new versions to F-Droid. I'm waiting for the version with less permissions (it's still on V1.0).
> 
> Thanks

I cannot push new versions to F-Droid by myself, but I need to create tags for versions (which I do - see [here](https://github.com/dslul/openboard/releases)) and wait for their systems to build them. They already indexed the [last two versions](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.dslul.openboard.inputmethod.latin.yml), but still no builds available.
