### ISSUE TITLE
Emoji are too hidden...

### ISSUE THREAD

**Issue by jedie** [dslul/openboard#104]
I didn't find the emoji. Because I didn't realized that I must press and hold the blue arror button bottom/right.

There are some screenshot that display a blue smiley button and not the "enter" button. That's better.

**Comment by marcdw1289** [comment]
The standard AOSP keyboard behaves in the same or similar manner. Been like that for ages.
I recommend getting familiar with that. A dedicated emoji button isn't necessary IMNSHO.

**Comment by sandsturm** [comment]
I am not a developer, @dslul decides if that gets implemented. But what would you expect? Where to put it?

**Comment by jedie** [comment]
Ah! #61 is the solution. So i close this here.
