### ISSUE TITLE
Improve Bulgarian wordlist and create dictionary

### ISSUE THREAD

**Issue by roshavagarga** [dslul/openboard#105]
This is for @sandsturm or anyone else that might have the time to do this. I have tried and failed numerous times to create a new dict file.

In my humble opinion, the original frequencies are way off, but amassing a lot of words to properly assess this is hard. Subtitles would skew the frequencies, as is evident in this dict, and would not allow for the addition of _offensive_ words.

Proposed changes:
1. Change line 1 to: (date needs to be properly filled in)
`dictionary=main:bg,locale=bg,description=Български,date=??????????,version=2`

2. Add these words (746, including derivatives) with frequencies set to 1:
https://hastebin.com/jebodehadu

3. Maybe add this to the end of every line for future-proofing:
`,flags=originalFreq=`

**Sources:**
* [Local cuisine names](https://ibl.bas.bg/kulinar/kulinarna-karta.html)
* [Word forms/derivatives](https://rechnik.chitanka.info/)
* [Old/dialect words](http://treasures.zonebg.com/dict.htm)
* [Turkish words in Bulgarian](https://bg.wikibooks.org/wiki/%D0%A0%D0%B5%D1%87%D0%BD%D0%B8%D0%BA_%D0%BD%D0%B0_%D1%82%D1%83%D1%80%D1%81%D0%BA%D0%B8%D1%82%D0%B5_%D0%B4%D1%83%D0%BC%D0%B8_%D0%B2_%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8%D1%8F_%D0%B5%D0%B7%D0%B8%D0%BA)

**Comment by sandsturm** [comment]
Hi @roshavagarga, sure, let's give it a try.

**Comment by roshavagarga** [comment]
On line 414887, there's a typo, probably happened when I was manually adding the words in Notepad++. That line should be `word=халът,f=1,flags=,originalFreq=`.

Besides that:
1. The empty flags were added only to the new words;
2. First line should read `Български` after description, instead of `български`. I'm basing this on the fact that most of the wordlists I saw listed the language name with a capital work in their description.

Besides that, I was able to find a handy number of frequency lists, both for Bulgarian and other European languages, located [here](http://dcl.bas.bg/BulNC-registration/#feeds/page/2). I think I'll be able to give you a more proper frequency list based on these + other texts in the future.

On a sidenote, any idea how emojilists are properly edited/made? Can't seem to find an encoding in Notepad++ that would allow me to see all of the symbols.

**Comment by sandsturm** [comment]
On my computer, line 414887 is `word=халалхалът,f=1,flags=,originalFreq=`. I guess you meant the update this line: `word=халал,f=1,flags=,originalFreq=` which looks similar to the word in your post. Tell me if this is correct, I will upload the corrected commit and request a new pull.

1. Yes. I added the empty flags only to the new words from your pastebin.
2. Updated! 

Yes. I do the same for the German language and will probably do it for the English language as well.

Emojilist: yes, I saw that there are a number of requests. I will have a look on this after this issue is closed.

**Comment by roshavagarga** [comment]
The line that has 'халалхалът' should have 'халът' instead. Notepad++ autocompleted it, because it already had 'халал'. One means 'halal', the other means 'the situation' (Turkish loanword).

If you feel up to it, you can add the flags to the old words too. Either way is fine by me.
How off was the German frequency compared to the original, out of curiosity? The lists I sent you actually have frequency lists for German, but the Bulgarian ones I checked out hadn't gone through a check, so there were some symbols/nonwords in there.

I'd be very interested, so tag me once you do get into it in the future (emojilists, etc.)

Thank you for the help once again, Martin!

**Comment by sandsturm** [comment]
Updated #108 with the changes

**Comment by sandsturm** [comment]
I am working on a tool to automate the calculation and generation of the dicts. I am currently working on the optimization of the performance. It is very slow at the moment. I will let you know!
https://github.com/sandsturm/aosp-create-dictionary-tools

**Comment by roshavagarga** [comment]
Sounds wonderful! Feel free to ping me once it's reached a point where you want to share it :)
Should I close now or once the pull request goes through?

**Comment by sandsturm** [comment]
By experience: once the pull requests goes through.

**Comment by roshavagarga** [comment]
@dslul Closing this, but might I suggest actually pushing out a release, since it's been 4 months since the last one?
