### ISSUE TITLE
Missing emojis

### ISSUE THREAD

**Issue by Stenafo** [dslul/openboard#112]
I'm having trouble with missing emojis
![Screenshot_20200605-172855](https://user-images.githubusercontent.com/15031098/83895103-88a6a180-a752-11ea-84e0-030e72f65cea.png)

**Comment by malekairmaroc7** [comment]
I guess they aren't supported by your phone's `NotoColorEmoji.ttf` in general.

**Comment by Stenafo** [comment]
How van I solve?
I have a Samsung galaxy s6

**Comment by malekairmaroc7** [comment]
Either download a emoji changer app (requires root) or search in the net for an up to date `NotoColorEmoji.ttf`.

**Comment by Stenafo** [comment]
Do you think I could make an apk without incompatible emoticons?

**Comment by malekairmaroc7** [comment]
I guess yeah sure. I wouldn't know why not. You just need to modify the right file.

**Comment by m-sameer** [comment]
@Stenafo [Unlock bootloader](https://forum.xda-developers.com/galaxy-s6) (may wipe all your data) and flash some ROM and you'll be good to go. 

You could use font-changer magisk module to install custom text fonts and emoji fonts. JoyPixels are the best currently. Your taste might differ.

**Comment by m-sameer** [comment]
This issue is clear to close.
