### ISSUE TITLE
[REQUEST] Keyboard Resizing more than 120%

### ISSUE THREAD

**Issue by TuxKruger** [dslul/openboard#113]
Hey dev,

I am really loving OpenBoard. It is so good to use and the keypress sounds, spell correction and other features make it pretty cool.
As you already know that the Keyboard Resize limit is 120% which is too low for a device with 20:9 aspect ratio. I would really appreciate if you increase Keyboard Resize limit just for the sake of newer phones!

Thank You!
I hope you will look forward to my humble request!

**Comment by Batcastle** [comment]
I would also like to add that it would help those of us with fat fingers type on a larger keyboard.

**Comment by dslul** [comment]
Fixed 41a4173cabf2c1c539fd037d5d6cfc1d45ad1d0f, now the max can be set to 150%.
