### ISSUE TITLE
[Feature request] Adding swype feature

### ISSUE THREAD

**Issue by Christian-Git01** [dslul/openboard#117]
Are there any plans on adding swype feature? Some information about this topic:
[jupyter notebook about gesture typing](https://nbviewer.jupyter.org/url/norvig.com/ipython/Gesture%20Typing.ipynb)

[paper by google](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43461.pdf)

**Comment by dslul** [comment]
Yes, but it's not a simple task for a single person. I'll close this as it's a duplicate of #3 .
