### ISSUE TITLE
[Feature request] Turn off full-screen in Landcape mode

### ISSUE THREAD

**Issue by rehork** [dslul/openboard#118]
Hello,

Would that be possible to have an option which switches off full screen on landscape view?  It might be easier to follow a chat in for instance Whatsapp. Also, in Whatsapp I wouldn't have to accept  a text I've already written twice to send it.

Cheers

**Comment by dslul** [comment]
not a single app I use required this stupid behaviour, so I was not aware. I disabled it for now in landscape mode. I could add a setting, but I don't think anyone is gonna miss it. Fixed 4ec21f97f6a422990c41ce6434bcdfd8a4aafc57.
