### ISSUE TITLE
Missing word suggestion in Incognito Mode

### ISSUE THREAD

**Issue by kojid0** [dslul/openboard#12]
When typing in a private/sensitive text field which has the flag  "IME_FLAG_NO_PERSONALIZED_LEARNING", word suggestion is not available. This is the case in my Browser's Incognito Mode and in Telegram Secret Chats, for example.

IMO it should be available but should simply not learn new word predictions or next-word-suggestions.

**Comment by jwsp1** [comment]
Also missing here:
- Browser URL text field (e.g. on Brave Browser for Android and Firefox for Android)
- Text field on https://www.startpage.com/
- Text field on github where you put the title of an issue

**Comment by dslul** [comment]
I already noticed this, it's definitely a [bug](https://github.com/dslul/openboard/blob/797ee4f5c616490e9fde04de09bbde0d55651172/app/src/main/java/org/dslul/openboard/inputmethod/latin/InputAttributes.java#L145) (I tried with omnirom keyboard and it has the same problem). I'll try to figure it out.

**Comment by francescosoave** [comment]
It's also missing in various other apps such as Duckduckgo, TransportTR, Simple File Manager, openScale, newPipe (all from F-Droid), Duolingo, Monefy (from Play Store)

**Comment by MisterY** [comment]
Related? #54

**Comment by theslimshaney** [comment]
Were you ever able to find out what's happening, or any pointers?

**Comment by dslul** [comment]
This should be solved with a6d7e2d3ac87b6335d9f118ef750e9c1cca7c97b. I should also add a toggle in settings, and do more testing to be sure to select all the right flags.

**Comment by theslimshaney** [comment]
Very nice! Will try to test it out

**Comment by dslul** [comment]
I'll close this for now as it should be solved.

**Comment by Tisckkytt** [comment]
With incognito icon (assuming it's active)
![Screenshot_20210109-143554.png](https://user-images.githubusercontent.com/56971216/104087191-1e298700-5288-11eb-910c-36705a94a4a1.png)

Without incognito (no icon)
![Screenshot_20210109-143747.png](https://user-images.githubusercontent.com/56971216/104087227-65b01300-5288-11eb-8610-3410b4cbabe1.png)

This is the official github app, no suggestions are presented on any of the text fields.

Version: 1.4.2 from github release.
