### ISSUE TITLE
[Feature request] Seperate number row

### ISSUE THREAD

**Issue by p4ddywhack** [dslul/openboard#121]
Could you add an option to have the number row seperately instead of having to long-tap to get to them?
Thanks

**Comment by mfortini** [comment]
Duplicate of #98

**Comment by nomad-skateboarding** [comment]
> Could you add an option to have the number row seperately instead of having to long-tap to get to them?
> Thanks

Already asked

**Comment by kojid0** [comment]
duplicate of #21
