### ISSUE TITLE
Pop up keys hangs while typing fast

### ISSUE THREAD

**Issue by awais1281** [dslul/openboard#125]
pop up keys hangs when I type fast, when I disable the auto-correct and suggestion this problem is resolved. This problem doesn't happen when I download app form play store, when I run form android studio it occurs.

**form hang I meant**: glitches while typing fast, popup keys stays longer on keyboard. You can recreate this issue by enabling auto correct and suggestion. and then try typing fast by disabling auto correct and suggestion you will feel the difference.

**Comment by ChildishGiant** [comment]
For me sometimes the writing of the text lags out as well and then catches up

**Comment by dslul** [comment]
@awais1281 this happens when you use a debug build, which is not optimized. nonetheless, performance is not on par with gboard and swiftkey and needs to be addressed.

**Comment by dslul** [comment]
This should be solved in 6de199cbcf4678feb9611e32eb858d648862d5bb .
