### ISSUE TITLE
[Feature Request] New Language Request (Urdu)

### ISSUE THREAD

**Issue by privacymentor** [dslul/openboard#126]
Please add Urdu language with support like gboard in which we type in Roman Urdu ( spell Urdu words in English and they automatically write in urdu transcript) and it should convert it into Urdu script in real time. This is the only feature I m missing on openboard.

**Comment by dslul** [comment]
@saammaibal I cannot implement this myself, since I don't know the language. Keep in mind that gboard has an entire team from different countries. You can use Indic keyboard, or try to integrate the parts you need here.
