### ISSUE TITLE
Hungarian spellcheck is not working

### ISSUE THREAD

**Issue by kresbeatz** [dslul/openboard#128]
Hi, it seems Hungarian spellcheck is not working, probably because I don't see Hungarian dictionary in 
openboard/app/src/main/res/raw/. It seems I found Hungarian dictionary in right format for Openboard here: https://github.com/LineageOS/android_packages_inputmethods_LatinIME/blob/lineage-17.1/dictionaries/hu_wordlist.combined.gz
But I really struggle to add it on GitHub due to lack of knowledge. Could somebody help, please?

**Comment by BasilTomato** [comment]
Hello dslul,
I have just updated to the latest version via AuroraStore (1.4 (11)), but the Hungarian dictionary is still missing at the moment.
Do you have a time frame on integrating this?
Thank you beforehand!

**Comment by dslul** [comment]
Fixed https://github.com/dslul/openboard/pull/271
