### ISSUE TITLE
[OB 1.4.1] %s keyboard ?

### ISSUE THREAD

**Issue by repsorp** [dslul/openboard#129]
OpenBoard 1.4.1 French keyboard is displayed as %s in Gboard "Change keyboard" menu list

Android 9 / OpenBoard 1.4.1
![Screenshot](https://i.imgur.com/5XOnGOD.png)

**Comment by dslul** [comment]
@repsorp how can I reproduce this?

![image](https://user-images.githubusercontent.com/6121202/94700139-73760400-033b-11eb-99ba-fc0bee74029d.png)

**Comment by repsorp** [comment]
In Gboard, long click on spacebar to change keyboard

**Comment by dslul** [comment]
I'm not sure, this looks like a GBoard issue to me, does it happen with other keyboards?

**Comment by repsorp** [comment]
Doesn't happen with keepass2android keyboard.
Maybe you could add French as a language to check on your system.

**Comment by dslul** [comment]
> Maybe you could add French as a language to check on your system.

I did, as you can see from my screenshot. But if it's a problem only with GBoard, I don't think I can fix it.

**Comment by repsorp** [comment]
@dslul Try to chance language and select Francese

**Comment by repsorp** [comment]
It's not big deal anyway, Gboard not even activated here in Manage Keyboards" :wink:

**Comment by dslul** [comment]
I can't reproduce even when setting French as main language

![image](https://user-images.githubusercontent.com/6121202/94910686-58bf9e80-04a5-11eb-86d0-d1072e313dae.png)
