### ISSUE TITLE
Wrong dictionary used for spell checking

### ISSUE THREAD

**Issue by Pierre-Yves83** [dslul/openboard#131]
Hello,

Device: HiSense A5 Pro CC (native languages: Chinese and US English only, with US English configured as system language)

I type mostly in french. Openboard with French as only enabled language works great, and words suggestion are in french as expected:
<img src="https://user-images.githubusercontent.com/26676619/90309081-3cf83d00-dee5-11ea-8833-43a2304eeae9.jpg" width="25%" height="25%">

However, spell checking uses the English dictionary, so all french words are underlined in red:
<img src="https://user-images.githubusercontent.com/26676619/90308932-27cede80-dee4-11ea-8a0b-04a308ce50f2.jpg" width="25%" height="25%">

And selecting one of these underlinded words opens a suggestions menu, which is based on the English disctionary content:
<img src="https://user-images.githubusercontent.com/26676619/90308934-30271980-dee4-11ea-8e69-ee6f2af4d8dd.jpg" width="25%" height="25%">

I was unable to locate any option for ensuring which dictionary was used for spell checking. I suspect that somehow the spell-checking is defaulting to the system language.

**Comment by dslul** [comment]
I can't reproduce your issue. Are you using openboard spell checker in the system settings?
