### ISSUE TITLE
spacebar-swipe to quickly find emojis [feature request]

### ISSUE THREAD

**Issue by aha999** [dslul/openboard#133]
While in the emoji menu, it would be awesome if we could hold the spacebar button and swipe left or right to very quickly swipe through all emojis at once. That way we can find the required ones faster without mindless repeatable swiping.

I've used this feature somewhere already.

(Other emoji finding features would also be awesome, since there is so many of them i have to strain to find them and go through a workout everytime to swipe through them to find the ones i'm looking for.)

**Comment by Oymate** [comment]
Maybe a search emoji feature?

**Comment by dslul** [comment]
This would collide with the current space swipe cursor functionality. Emoji search is discussed here: #35.
