### ISSUE TITLE
Spanish and Swedish dictionaries not working 

### ISSUE THREAD

**Issue by TheCrowned** [dslul/openboard#143]
I am a bit confused as to how Swedish and Spanish dictionaries are supposed to work, if they are. I simply get no suggestions while writing in neither langiage. It is now starting to suggest words I have previously typed, but definitely not drawing from a dictionary.

One example:
![Screenshot_Fennec_F-Droid_20200909-190718](https://user-images.githubusercontent.com/7880569/92630211-c8d86b80-f2cf-11ea-9800-146ac38b953d.png)
Expected suggestion: gick.

**Comment by kojid0** [comment]
There are no suggestions from a dictionary. Someone suggested this enhancement in #42 but unfortunately it was closed.
You will only see suggestions of words that you have previously written. No "global" suggestion.

**Comment by TheCrowned** [comment]
But then I wonder what is the point of having dictionaries?

**Comment by kojid0** [comment]
Eliminate typos only, I guess

**Comment by TheCrowned** [comment]
Is this the case @dslul? If yes, wouldn't it be nice to also use them for words prediction. I understand that it is more accurate to rely on user-entered input, but it is also so much convenient to be able to rely on a dictionary. For ex., it is particularly useful when learning a language - when you don't know exactly the spelling of a word you _kind of know_, but not exactly. Then being suggested it is so nice!

**Comment by kojid0** [comment]
I'm afraid there are no possibilities to obtain word suggestions. I doubt that there's a open source next-word suggestion dictionary. I have made a suggestion to fix this issue in #42

**Comment by TheCrowned** [comment]
> I doubt that there's a open source next-word suggestion dictionary.

Is it because it involves a lot of work, or because it clashes with anonymity? 
I can see that we don't want to rely on a wide user-generated database of most used words (and this I had not thought about before), but still, doesn't it exist a simple dictionaries where words are alphabetically in the first char, and then by usage? In that case, typing `s` would just require picking the first three entries of the `s` section. But maybe I am dreaming here...

**Comment by dslul** [comment]
The language dicts we have only store frequency information, like this:
```
 word=frontiers,f=91,flags=,originalFreq=91
 word=frustrating,f=91,flags=,originalFreq=91
 word=fuck,f=91,flags=offensive,originalFreq=91,possibly_offensive=true
 word=fueling,f=91,flags=,originalFreq=91
 word=functor,f=91,flags=,originalFreq=91
```
I like the way it works, maybe because I've used it for the past 6 years, I don't know. By the way, the problem here is getting a good dictionary. These were made by Google for AOSP.

**Comment by TheCrowned** [comment]
But how are they used exactly, if suggestions come from words the user previously entered themselves?

**Comment by dslul** [comment]
> But how are they used exactly, if suggestions come from words the user previously entered themselves?

Does it work in English or Italian? From what I understand, you don't get any correction at all, which should not happen.

**Comment by TheCrowned** [comment]
I think I now understand the expected behavior. I do get corrections in Spanish, see example

![Screenshot_Messaging_20200910-071451](https://user-images.githubusercontent.com/7880569/92684807-99a91500-f336-11ea-99c1-1ad3b1ed070f.png)

However, not in Swedish. Both `trädgården` and `strumpor` are real, correct words in Swedish


![Screenshot_Messaging_20200910-071520](https://user-images.githubusercontent.com/7880569/92684897-d96ffc80-f336-11ea-8a40-e51f3706f009.png)
![Screenshot_Messaging_20200910-071555](https://user-images.githubusercontent.com/7880569/92684907-decd4700-f336-11ea-9de4-4f4255230b10.png)
![Screenshot_Messaging_20200910-071604](https://user-images.githubusercontent.com/7880569/92684910-e260ce00-f336-11ea-894a-82d05e2a98d3.png)

**Comment by dslul** [comment]
There is no Swedish dictionary at the moment, so that's normal.

**Comment by TheCrowned** [comment]
Ah, now I understand! So the languages selection in the OB settings is used to control the keyboard layout (and then the dictionary is added on top only if available). Is that right?

**Comment by dslul** [comment]
> Ah, now I understand! So the languages selection in the OB settings is used to control the keyboard layout (and then the dictionary is added on top only if available). Is that right?

Correct. It's translated in a lot of languages, both only few of them have a dictionary for autocorrection

**Comment by jpds** [comment]
There's a pull request for a :sweden: dictionary at #116.
