### ISSUE TITLE
Please add more classical text smileys or even better let the user add them

### ISSUE THREAD

**Issue by l3u** [dslul/openboard#144]
I personally love to still use the classic text smileys, like :-) or ;-) or :-D or :-( or :'-( and so on. Currently, the emoticon selection dialog only lists a few of those new-fangled unicode ones (flipping table over).

I'd really love to be able to select the classical ones there, the very best thing would be if one could define own smileys to be shown.

Along with issue #61 and #6 , this would imo greatly improve the usability of the emoticon dialog.

**Comment by dslul** [comment]
@l3u I added some more b7c88b48d69ce50d6a0391d1ad6ac6c52c768730

**Comment by l3u** [comment]
Thanks :-)

Maybe some more? I'd additionally add those:

;-)
:-(
:'-(

**Comment by kojid0** [comment]
@l3u should be done in e077915d7dc51a50c7963b5a3b21d6b592dd6a8c

**Comment by l3u** [comment]
Nice! Thank you :-)

**Comment by l3u** [comment]
The added smileys have been removed again with 6498de22cd611f954498e738f241d48f894866fc – why?

**Comment by dslul** [comment]
I was having some issues at compile time, but didn't have much time to investigate why
