### ISSUE TITLE
Key popup dismiss delay cannot be changed from default in 1.4

### ISSUE THREAD

**Issue by Pentaphon** [dslul/openboard#145]
When installing, neither option is selected and once you select default you can't change it to "no delay".

**Comment by dslul** [comment]
That setting is useless now, I removed the popup delays because they were only causing lag during typing. I'll remove that setting in the next point update.

**Comment by Pentaphon** [comment]
> I removed the popup delays because they were only causing lag during typing. I'll remove that setting in the next point update.

Good. I don't know why anybody would change it anyway but I noticed it had no setting when examining the new release.

**Comment by dslul** [comment]
Removed in 1.4.1.
