### ISSUE TITLE

[OB 1.4.1] Material Dark no border (not AMOLED) ?

### ISSUE THREAD

**Issue by repsorp** [dslul/openboard#146]
OpenBoard 1.4.1
Material Dark no border (not AMOLED) is missing...

**Comment by dslul** [comment]
@repsorp I'll reintroduce it in the next update, sorry for the inconvenience

**Comment by dslul** [comment]
I forgot to do it for the 1.4.1, but I did it in the last commit 6532ed54dff2b341360d26b86c956fecaeb4c389 .
