### ISSUE TITLE
Which features does this provide over AOSP Keyboard?

### ISSUE THREAD

**Issue by n1trux** [dslul/openboard#15]
You say openboard is "based on" AOSP Keyboard.

Are there any features not present in AOSP Keyboard or is it just a rebrand currently?

**Comment by dslul** [comment]
@n1trux very little currently. I used to compile this on stock roms to have a blob-free keyboard (aosp uses liblatinimegoogle if it founds it) and had to change name when I switched to omnirom (it doesn't have special characters on long press there). There are also a couple of themes from simple keyboard (which I used for a while, but it doesn't have many useful features). I'll try to add some features in my free time.

**Comment by n1trux** [comment]
Thank you!

Maybe add a notice about this in the README and possibly link a "sister project":

https://github.com/AnySoftKeyboard/AnySoftKeyboard
