### ISSUE TITLE
spacebar trackpad

### ISSUE THREAD

**Issue by UserX404** [dslul/openboard#158]
Hello!
The spacebar trackpad needs more fine tuning. Sometime if i want to insert a space, the cursor is moved somewhere back in the middle of the written text.
It seems the trigger-distance for the swipe is too small.

Thank you!

**Comment by dslul** [comment]
@UserX404 what version are you using? F-Droid or Play Store?

**Comment by UserX404** [comment]
@dslul 
1.3
latest Version from F-Droid

**Comment by dslul** [comment]
@UserX404 The F-Droid version is quite old, this problem was fixed in 1.4 (1.4.1 is currently available from here).

It usually takes some weeks for the F-Droid version to catch up, mainly because they have to build everything from sources (you can check [here](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=30&from=&hidebots=0&hideanons=1&hideliu=1&limit=500) that openboard was built correctly).

**Comment by UserX404** [comment]
Ok, thanks.
So i have to wait for 1.4.1.
What do you mean with "from here"? Github?
1.3 is the most recent version at F-Droid.

**Comment by dslul** [comment]
> Ok, thanks.
> So i have to wait for 1.4.1.
> What do you mean with "from here"? Github?
> 1.3 is the most recent version at F-Droid.

I usually publish the apk also here in the [releases](https://github.com/dslul/openboard/releases) tab, signed with my private key (it's the same I upload to the play store).

**Comment by UserX404** [comment]
@dslul 
May you throw an eye on [this](https://f-droid.org/wiki/index.php?title=org.dslul.openboard.inputmethod.latin/lastbuild_12&redirect=no).
It seems there are some problems.

**Comment by dslul** [comment]
The issue is that [here](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.dslul.openboard.inputmethod.latin.yml#L28) the fdroid build server uses ndk r20 but I have set r21 in android.ndkVersion.

**Comment by dslul** [comment]
I removed my previous comment, because they actually set the [correct ndk](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.dslul.openboard.inputmethod.latin.yml#L39) for the latest version. I honestly don't know why it is failing.

**Comment by kojid0** [comment]
> I removed my previous comment, because they actually set the [correct ndk](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.dslul.openboard.inputmethod.latin.yml#L39) for the latest version. I honestly don't know why it is failing.

You might want to ask them for guidance on twitter or so.

**Comment by UserX404** [comment]
Closing as an new issue was created https://github.com/dslul/openboard/issues/162
