### ISSUE TITLE
Number row for international keyboards

### ISSUE THREAD

**Issue by UX0l0l** [dslul/openboard#159]
so, this is more of an enhancement than an issue for me. but I was wondering if you guys could add a number row for keyboards other than english. I use numerous other keyboards, like greek and arabic, and I noticed none of them have a number row, and it would just be much more convenient for me if there was a number row there for easy access

thank you for your time and efforts

**Comment by kojid0** [comment]
I'll try to add it and make a PR.

**Comment by UX0l0l** [comment]
> I'll try to add it and make a PR.
ok thx a lot dude

**Comment by kojid0** [comment]
@UX0l0l Done in a036cc9a2394e1183e032b7c19debc804619a03d
