### ISSUE TITLE
F-Droid version has not updated since 1.3

### ISSUE THREAD

**Issue by Pentaphon** [dslul/openboard#162]
Please investigate this issue so we can get your keyboard on F-Droid. 

https://f-droid.org/packages/org.dslul.openboard.inputmethod.latin/

**Comment by l3u** [comment]
I really appreciate OpenBoard to be on F-Droid. Please keep it updated there so that one won't be forced to install it from Play Store!

**Comment by Pentaphon** [comment]
> I really appreciate OpenBoard to be on F-Droid. Please keep it updated there so that one won't be forced to install it from Play Store!

Somebody else reported it was stuck https://gitlab.com/fdroid/fdroiddata/-/issues/2182

**Comment by dslul** [comment]
Builds keep failing https://f-droid.org/wiki/index.php?title=org.dslul.openboard.inputmethod.latin/lastbuild_12&direction=next&oldid=279025

@licaon-kter any clue?

**Comment by licaon-kter** [comment]
13 already built: https://f-droid.org/wiki/page/org.dslul.openboard.inputmethod.latin/lastbuild_13

/close this and wait for publishing ;)

**Comment by Pentaphon** [comment]
> /close this and wait for publishing ;)

Done
