### ISSUE TITLE
German QWERTZ keyboard with Umlauts (ÖÄÜ)

### ISSUE THREAD

**Issue by BoltCitizen** [dslul/openboard#168]
German QWERTZ keyboard with Umlauts (ÖÄÜ) would be great

**Comment by kojid0** [comment]
They are available, or what do you mean?
![openboard](https://user-images.githubusercontent.com/24477557/95311895-8aae7780-088e-11eb-89ba-1f8c73954c7d.jpg)

**Comment by BoltCitizen** [comment]
I mean as a seperate letter, like they are on a German keyboard. Similarly how the Ñ is a seperate letter on the Spanish keyboard

**Comment by kojid0** [comment]
Like this? (from Anysoftkeyboard)

![anysoftkeyboard](https://user-images.githubusercontent.com/24477557/95312239-f8f33a00-088e-11eb-8180-6d8d7be57439.jpg)

**Comment by BoltCitizen** [comment]
Yes, exactly!

**Comment by BoltCitizen** [comment]
Not a big issue, more of a nice to have. (Multilanguage spellcheck is way more important imho)

**Comment by kojid0** [comment]
I'd probably be able to do this but unfortunately I don't have the possibility to test since I'm unable to create a test apk as described [here ](https://github.com/dslul/openboard#apk-development). 
Therefore I cannot do major changes to the app, just small ones which work when I code "blindly". 
So when you tell me more detailed how to develop apk with Windows, ZorinOS or Manjaro, I can help you :-)

**Comment by dslul** [comment]
> I'd probably be able to do this but unfortunately I don't have the possibility to test since I'm unable to create a test apk as described [here ](https://github.com/dslul/openboard#apk-development).
> Therefore I cannot do major changes to the app, just small ones which work when I code "blindly".
> So when you tell me more detailed how to develop apk with Windows, ZorinOS or Manjaro, I can help you :-)

You shouldn't have problems with Android Studio, just open the directory, download what it tells you and it should work.

**Comment by kojid0** [comment]
> You shouldn't have problems with Android Studio, just open the directory, download what it tells you and it should work.

I know, I already worked with Android Studio for a while but I can't get openboard building there. Maybe the same reason why F-Droid is stuck with an old version?
I'm getting this error: `executing external native build for ndkBuild C:\Users\user\openboard\app\src\main\jni\Android.mk`

**Comment by kojid0** [comment]
@dslul do you know in which file the spanish keyboard layout is set? There's `rowkeys_spanish2.xml` and I tried to add similar xml but German layout uses normal qwertz layout and isn't "linked" to my created `rowkeys_german_umlaute1.xml` (for ü) or `rowkeys_german_umlaute2.xml` (for ö and ä) or `rowkeys_german_umlaute3.xml` (for ß)...There must be a file telling openbaord to use the different rowkeys (qwertz, qwerty, spanish,...)

Also, is it the correct approach to add another "language" for German Umlaute layout? Like there are 3 keyboard languages for Spanish (Spanish, Spanish Latin America and Spanish USA). I'd create German and German Umlaute?

**Comment by kojid0** [comment]
@BoltCitizen Check out "German (Switzerland)" layout, this has umlauts included. Don't know if there's a difference in spell check though. Can you test and give feedback?

**Comment by derhagen** [comment]
Working on this

**Comment by derhagen** [comment]
Proposal: Keep the "German" keyboard as it is, based on the standard QWERTZ keyboard. Add a "German (Germany)" keyboard that's similar to the swiss one but uses German spell check. Also, it prefers numbers over Umlauts when you press "o" and "u" longer, since Umlauts get dedicated keys.
