### ISSUE TITLE
Plan for long term maintenance

### ISSUE THREAD

**Issue by dkanada** [dslul/openboard#17]
I'm not quite sure if the AOSP keyboard is getting any updates now that Google is basically deprecating all their open source apps, but how do you usually handle merging your changes with upstream? It might be nice to keep all (or at least most) changes as a list of patches that can be applied to a fresh clone of the AOSP keyboard.

**Comment by dslul** [comment]
Google unfortunately abandoned aosp keyboard many years ago, they continued it's development in gboard (which is closed source).
