### ISSUE TITLE
Add changelog to F-Droid (e.g. by using fastlane)

### ISSUE THREAD

**Issue by jwsp1** [dslul/openboard#171]
There is no changelog in F-Droid. If you use [fastlane](https://fastlane.tools/), it will automatically be created. 
More here https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ 
and a nice short description here https://gitlab.com/snippets/1895688

**Comment by dslul** [comment]
I'm already using fastlane https://github.com/dslul/openboard/tree/v1.4.2/fastlane/metadata/android/en-US/changelogs

**Comment by jwsp1** [comment]
That is odd, will recheck when v1.4.3 or 1.5 arrives and close this issue then.

**Comment by jnnkB** [comment]
@dslul I think you have to rename the file from `1.4.3.txt` to `15.txt` cause if I have understood the [f-droid docs](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure) correctly the file name should be the versionCode and not the versionName. And the versionCode is 15 according to the [build.gradle](https://github.com/dslul/openboard/blob/d50265f04d0905b18f4b62471574ca8b046b5e6f/app/build.gradle) file.

**Comment by dslul** [comment]
Didn't know that, thanks! I'll fix it for the next release.

**Comment by dslul** [comment]
fixed
