### ISSUE TITLE
Spacebar moving the cursor [feature request]

### ISSUE THREAD

**Issue by aha999** [dslul/openboard#173]
The iphone keyboard has this option that when you hold the spacebar and move it left/right, it moves the text cursor left/right instead of having to put your finger on where you want to edit the text.

Please add the spacebar cursor moving capability.
More about this: https://archive.vn/7PSOO

**Comment by dslul** [comment]
Try to do it, it's already implemented :) (but you don't need to long-press here, just swipe)

**Comment by aha999** [comment]
Woah, thanks!

**Comment by gbdomubpkm** [comment]
The necessary mechanism was essential to move the cursor on the same line, but insufficient.
It should also be possible not only to move the cursor from right to left, but also from top to bottom (change line), which would consist in freezing the keyboard as long as you press your finger on it to make the swipe movement in the desired direction (by initially pressing the space bar).
