### ISSUE TITLE
Numeric layout not showing up on tablet

### ISSUE THREAD

**Issue by nickdurante** [dslul/openboard#176]
While the numeric layout works great on my smartphone, using the tablet it displays a black screen, on number only field.
This happens in both landscape and portrait mode on my Galaxy Tab A.

Steps to reproduce the issue:
1. Open a number only field on a tablet, such as contact number

**Comment by trymeouteh** [comment]
This is also the case on the samsung galaxy tab s4

**Comment by dslul** [comment]
Do you know if this bug was present in v1.3?

**Comment by nickdurante** [comment]
Yes, I've encountered the same issue in v1.3.
If you need some adb logcat, I can record some.

**Comment by licaon-kter** [comment]
Confirmed for me with 1.4.2 on a 10" chinese OEM tablet, Android 10, trying to enter the number pin in F-Droid Firefox 83 on https://kahoot.it but Openboard just crashes.

No issue with Simple Keyboard.

Will try to extract a log.

**Comment by dslul** [comment]
Fixed 6796bd88bd8d06ab9ce147aabdedde2faa415390. I should have addressed this sooner, but I needed a tablet to reproduce the issue.
