### ISSUE TITLE
Polish default dictionary not working

### ISSUE THREAD

**Issue by Kendbi** [dslul/openboard#18]
While using polish dictionary only suggested words appearing are the ones I had already written on my own.

**Comment by dslul** [comment]
I added the polish dictionary in the latest commit 7b9f21607c7b0833bffea924787a48128cc7725f

**Comment by gjallarhorn** [comment]
Would it be too extreme to add all of the European languages (24)? Made a quick calculation and the total size for adding the ones missing, would be around 20 MB.

**Comment by dslul** [comment]
> Would it be too extreme to add all of the European languages (24)? Made a quick calculation and the total size for adding the ones missing, would be around 20 MB.

It could be done, I wrote some instructions in the readme on how to add languages, it's very simple if you already have the dictionary (like these https://github.com/dslul/openboard/tree/master/dictionaries)

**Comment by MisterY** [comment]
@dslul, 

> I wrote some instructions in the readme on how to add languages

I don't see these instructions in the readme. There is only mention of how to create dictionaries. Guess it should be obvious from reading the code? Let me try. :)

**Comment by dslul** [comment]
> I don't see these instructions in the readme. There is only mention of how to create dictionaries. Guess it should be obvious from reading the code? Let me try. :)

I know, I didn't wrote great instructions, anyway it's really simple, just download dicttool (from that link) and then, from command line, convert to binary the dictionary:
`java -jar dicttool_aosp.jar makedict -s en_wordlist.combined -d main_en.dict`
where en_wordlist.combined is the text wordlist (there are some - compressed - in the dictionaries folder, not all were converted to binary). main_it.dict is the output, it should be put in the res folder. Of course, change "en" with the language specified in the dict.

**Comment by dslul** [comment]
@Kendbi I added polish in v1.3, if it doesn't work for you, I'll reopen this issue.

**Comment by thecrazyblack** [comment]
Sir @dslul sorry for spam here. Can you help ppl on https://github.com/remi0s/aosp-dictionary-tools/issues/1 to fix this? I have same issue :( TIA
