### ISSUE TITLE
Number keyboard not working on tablets

### ISSUE THREAD

**Issue by trymeouteh** [dslul/openboard#186]
When I select a input on a website that is a number type, this is how it appears on my tablet. I have had this issue for months.

![Screenshot_20201012-210743_Brave](https://user-images.githubusercontent.com/31172274/95810852-26951480-0ccf-11eb-88d8-e6afcc99cfb7.jpg)

**Comment by dslul** [comment]
Closing as duplicate of #176

**Comment by dslul** [comment]
Fixed 6796bd88bd8d06ab9ce147aabdedde2faa415390.
