### ISSUE TITLE
suggestions from multiple dictionaries

### ISSUE THREAD

**Issue by francescosoave** [dslul/openboard#19]
Hi, first of all thanks a lot for the project I've been looking for FOSS keyboards alternatives for a long time!
One feature I miss at the moment is to have suggestions from multiple dictionaries at the same time.
I usually write in 2 different languages and I'd like to receive suggestions from both (based on the word I'm typing).

Thanks!

**Comment by jwsp1** [comment]
Duplicate #7

**Comment by dslul** [comment]
Hi @francescosoave, this feature is already planned for the future. I'll close this as duplicate since there is already an issue.
