### ISSUE TITLE
Split keyboard does not work with other languages

### ISSUE THREAD

**Issue by Donotoknow** [dslul/openboard#191]
Split keyboard functions only with English USA, not any other language.

**Comment by derhagen** [comment]
At least it works in German (QWERTY), so I guess it's limited to QWERTY-layouts and not just English (USA).

**Comment by derhagen** [comment]
If you feel like giving it a try, have a look at the difference between

- https://github.com/dslul/openboard/blob/master/app/src/main/res/xml/rowkeys_qwertz1.xml
- https://github.com/dslul/openboard/blob/master/app/src/main/res/xml/rowkeys_qwerty1.xml

Then, add `latin:supportsSplitLayout="true"` to the `alphabet` Element in https://github.com/dslul/openboard/blob/master/app/src/main/res/xml/keyboard_layout_set_qwertz.xml

**Comment by derhagen** [comment]
@Donotoknow created a PR for QWERTZ. Do you need any other layout?
