### ISSUE TITLE
Language request: Chinese, Japanese

### ISSUE THREAD

**Issue by Manothave** [dslul/openboard#200]
Language request: Chinese, Japanese

**Comment by modestderp** [comment]
+1 for Chinese support

Personally I specifically need Traditional Chinese support on Openboard with **Hanyu Pinyin** input
If Traditional Chinese works, then I can ditch GBoard completely
Switching between Openboard and Trime when typing is too cumbersome for prolonged use...

**Comment by fishman** [comment]
I have the same issue, what is necessary to add this?

**Comment by jnnkB** [comment]
Duplicate of #192
