### ISSUE TITLE
[Feature Request] Allow to use multiple languages for a same layout

### ISSUE THREAD

**Issue by lululock71** [dslul/openboard#208]
Hi,
The title may be confusing but the idea is that I type mostly in French and in English and so far, I've used SwiftKey, which allows to pair the keyboard layout/dictionary as we please. I wanted to switch to a open source solution, for privacy reasons, so I got rid of SwiftKey.

Openboard should allow some combinations like that, so I could use the AZERTY layout with the English dictionary.

Maybe there's an option but I couldn't find it...

**Comment by Marcool04** [comment]
Yeah, this can already be done:
OpenBoard Settings -> Appearance & Layouts -> Customised input styles
Click on the ⊕ in the top right.
Select **the language you want a non standard layout for**, say, for example, French, then the layout QWERTY (French normally has AZERTY). The app prompts you to activate this new "language" (actually a language-layout combo), do so.
Good to go!

**Comment by nathanpuch** [comment]
@Marcool04 I am not sure this is the feature @lululock71 is asking about. I have the same problem as him and what you're suggesting is a good temporary option but not the feature we would like.

The feature would be being able to set up multiple dictionaries for a single language-layout combo. It would allow us to type in French and English without having to change language-layout combo by long-pressing the space bar (this would especially be helpful for conversations where we mix French and English). This feature is actually available in SwiftKey.

**Comment by Marcool04** [comment]
Oh, my mistake, I misunderstood, the original question is not very very clear, your formulation @nathanpuch is much clearer. So this is purely a spellcheck issue. You could possibly work around this by creating your own dictionary by combining two language dictionaries? Not sure how hard that would be to do…

**Comment by chohner** [comment]
I believe there is already an issue open here: https://github.com/dslul/openboard/issues/167
