### ISSUE TITLE
[Feature Request] Add BÉPO keyboard layout for French.

### ISSUE THREAD

**Issue by lululock71** [dslul/openboard#209]
Hi,
The French BÉPO keyboard layout is missing from the available layouts.

**Comment by mirsella** [comment]
there is a LOT of different keyboard layout. imo the best solution would be to add a feature to add custom layout. we can probably with not too much pain recompile the app with a different layout.

**Comment by mirsella** [comment]
i have it on the latest google play release

**Comment by jrd** [comment]
I have et top. A bit hard to fins thé settings. Works in French and English. But maybe the layout is bundled elsewhere. I have a Lineage ROM.

The layout is a bit weird though: no direct è. No direct quote (neither straight nor curved). Most letters have no option oh long press. So I'm not sure it worse it like that

**Comment by jrd** [comment]
Here some screenshots
![Screenshot_20201215-211019_Fennec](https://user-images.githubusercontent.com/497895/102267321-0590b000-3f1a-11eb-85ff-faf7e03c0aba.png)
![Screenshot_20201215-211002_Fennec](https://user-images.githubusercontent.com/497895/102267331-07f30a00-3f1a-11eb-80e8-3b9a1c2db4c8.png)
