### ISSUE TITLE
Numbers row

### ISSUE THREAD

**Issue by AlanSanchezP** [dslul/openboard#21]
It would be nice to have an option to enable/disable a row for numbers so long-pressing is not necessary.

**Comment by jwsp1** [comment]
@dslul you might want to check this aosp keyboard which actually works quite the same as yours is. It contains the option to show numbers row:

https://github.com/rkkr/simple-keyboard

**Comment by jwsp1** [comment]
When adding numbers row, we will have the whole first row for new secondary keys (e.g. currently Q shows 1, W shows 2,...) .
Not sure why A and S don't have visible secondary keys (e.g. A could have @) but you might want to check how SwiftKey is playing secondary keys.

![Screenshot_20200131_202641](https://user-images.githubusercontent.com/24477557/73568104-089cc200-4468-11ea-9ce0-337d2e2017fc.jpg)
![Screenshot_20200131_202627](https://user-images.githubusercontent.com/24477557/73568112-0cc8df80-4468-11ea-9726-57c19bac89f2.jpg)

**Comment by malekairmaroc7** [comment]
But I would do it as an option. Not permanent.
