### ISSUE TITLE
Incognito tab can't work 

### ISSUE THREAD

**Issue by Pranab009** [dslul/openboard#215]
Incognito tab shown but it can't on/off from here.

**Comment by jnnkB** [comment]
What do you meen by that. Do you want to enable and disable the incoginto mode? As far as I understand it it's automatically enabled based on context (for example when using a browser in incognito mode. It also can be forced in OpenBoards advanced settings.

**Comment by Pranab009** [comment]
Thanks for your response.
Now I understand.

**Comment by jnnkB** [comment]
Can this issue then be closed?

**Comment by Pranab009** [comment]
Ok
