### ISSUE TITLE
URL Suggestion problem

### ISSUE THREAD

**Issue by 2ndemosthenes** [dslul/openboard#218]
The suggestions don't continue after using some punctuations and numbers.

Steps to reproduce.
1.Write a word, like "github" 
2.Write "."
3.The suggestions would restart, so it wouldn't suggest something like "github.com".

The same problem exists with email addresses or in words that contain numbers in them even if a word that contain these has been added to the User Dictionary.

Android OS version:
8

Device manufacturer and model:
Huawei Y7
2018

**Comment by kojid0** [comment]
Typing email addresses with openboard drives me crazy as well...

**Comment by dslul** [comment]
Fixed https://github.com/dslul/openboard/pull/384

**Comment by guygadebois** [comment]
Hi, I'm eager to get this fix (very annoying when typing email addresses). Do you know when will a new release be built to include the fix?
Thanks in advance!
