### ISSUE TITLE
Open settings from keyboard

### ISSUE THREAD

**Issue by AlanSanchezP** [dslul/openboard#22]
Currently it has the settings shortcut but when I try to use it nothing happens. (Using it on MIUI 11, android 9, redmi 6)

**Comment by dslul** [comment]
You need to long-press the comma button, the other one is for changing keyboard, but I should add a little gear icon on top to avoid confusion.

**Comment by AlanSanchezP** [comment]
I know, but when I tap "OpenBoard settings" the keyboard closes but nothing else happens.

**Comment by dslul** [comment]
> I know, but when I tap "OpenBoard settings" the keyboard closes but nothing else happens.

That's strange, I can't reproduce this, what version do you have?

**Comment by AlanSanchezP** [comment]
1.0 from f-droid

**Comment by Newbytee** [comment]
I have a similar issue. However, in my case, I'm told that OpenBoard crashed. This is also with 1.0 from F-Droid, however on a HTC One M8s (not M8) running Android 6.0.

**Comment by dslul** [comment]
Could you please post a stack trace? I don't know how to reproduce this, it doesn't happen on my phones (I tried both android 9 and 6)

**Comment by Newbytee** [comment]
> Could you please post a stack trace? I don't know how to reproduce this, it doesn't happen on my phones (I tried both android 9 and 6)

Sure, however I'm not very familiar with Android development and debugging. Any pointers to how I would do this? Do I need to use adb?

**Comment by dslul** [comment]
> Sure, however I'm not very familiar with Android development and debugging. Any pointers to how I would do this? Do I need to use adb?

Either with adb logcat, or with an app like syslog (I don't know if it works without root)

**Comment by Newbytee** [comment]
I think this is it [logcat.txt](https://github.com/dslul/openboard/files/4102804/logcat.txt)

**Comment by dslul** [comment]
Thanks, should be fixed now 067a8bf190cf6bc77fe3894192657c4fc33c7179
