### ISSUE TITLE
[Feature Request] - Arrow keys to move cursor like the one in Any Soft Keyboard

### ISSUE THREAD

**Issue by shivasagarrao** [dslul/openboard#223]
If Arrow keys are available on keyboard they help in moving cursor easily.

**Comment by UserX404** [comment]
Swipe over space bar is available and there is no need for arrow keys.

**Comment by shivasagarrao** [comment]
I don't know regarding that feature. Yes there is no need for arrow keys. Openboard has implemented moving cursor more efficiently when compared to Any soft keyboard because arrow keys require additional space whereas space bar don't really need additional space.

**Comment by leaumar** [comment]
Personally I would like an option for arrow keys. Sure, they take extra space, but that's a user's choice to make, especially with the crazy display ratio on today's phones (I just went from my 5 year old 16:9 to 20:9).
I find the space bar cursoring clunky, especially for fine moves. I often either drag too slowly, resulting in nothing and then a "long press" action, or overshoot and need to correct again. Arrow keys would work very well for me instead.

Please reconsider.

**Comment by lucamp** [comment]
The actual trackpad does not go up and down. It will be a nice feature
