### ISSUE TITLE
We need this feature

### ISSUE THREAD

**Issue by zz1616611** [dslul/openboard#235]
1. Unlimited number of clipboard manager
2. Hope to support Google Text-to-Speech Speak phonetic letters are spoken when long pressing on keyboard keys and navigating by character. Applied to language learning. Pronunciation.[https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213](url)

**Comment by mirsella** [comment]
maybe you can make the title more explanatory. I'm not the dev but adding a text to speech engine would be a big feature, furtbermore it needs to be a open source engine.

**Comment by mirsella** [comment]
just installed the app and there is a text to speech managed by your phone

**Comment by Pantyhose-X** [comment]
Always speak typed keys Speak phonetic letters Phonetic letters are spoken when long pressing on keyboard keys and navigating by character.
Applied to language learning. Pronunciation correction

* example，https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213
The mother tongue is not English. Need to learn English, the market is very large

[Google Text-to-Speech apk](https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en_US&gl=US) 
[Mozilla's Text-to-Speech](https://github.com/mozilla/TTS)  
[coqui-ai TTS](https://github.com/coqui-ai/TTS)
