### ISSUE TITLE
Ability to choose language AND keyboard layout

### ISSUE THREAD

**Issue by gschurck** [dslul/openboard#240]
The setting to choose the language is integrated on the phone, but I can't choose for example english language with French AZERTY layout. Could you please add this option ?
Thanks.

![Screenshot_20201208-230751.jpg](https://user-images.githubusercontent.com/21091232/101547226-3d43a900-39aa-11eb-99b2-ba0efedb3c68.jpg)
![Screenshot_20201208-230801.jpg](https://user-images.githubusercontent.com/21091232/101547241-40d73000-39aa-11eb-9e76-ce526877c0d5.jpg)

**Comment by slaecker** [comment]
+1
I'd love to type English with QWERTZ layout.

**Comment by jnnkB** [comment]
You can create such an custom input style in the settings in Appearance & Layouts/Custom input styles.

**Comment by gschurck** [comment]
@jnnkB OK thanks
