### ISSUE TITLE
Dvorak keyboard layout

### ISSUE THREAD

**Issue by JojiiOfficial** [dslul/openboard#243]
Is it possible to set the keyboard layout to dvorak?

**Comment by lens17** [comment]
Yes it is. In the app, go to 'Layouts' and find the entry 'Custom Layouts'. There you can adjust the keyboard layout for each language. Options include, beneath others, qwertz, qwerty and dvorak. 
Btw: the entries in the settings are displayed in my phones language (which is not english), so I tried to translate the entries. Apologies, if they are translated wrong.

**Comment by JojiiOfficial** [comment]
After some more time I found it. It's not that intuitive because the list with the available languages/layouts already seemed pretty big so I assumed the dvorak layout was not supported at all. Thanks for your reply!
