### ISSUE TITLE
Blinking

### ISSUE THREAD

**Issue by dimqua** [dslul/openboard#25]
Keyboard blinks every time when I switch the language. This is very annoying behavior:
![](https://user-images.githubusercontent.com/540898/72697353-c95d9f80-3b50-11ea-82f5-a647a3ec9dc1.gif)
I do not have this problem with AOSP keyboard.

**Comment by dimqua** [comment]
It seems when both (AOSP and OpenBoard) keyboards are installed, they could conflict somehow.

**Comment by dslul** [comment]
They don't actually conflict. That button simply changes the current keyboard with the next one.
