### ISSUE TITLE
Is OpenBoard still being develloped?

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dslul/openboard#250]
There still are some big poblems like the German Layout (the `ß` specifically) being messed up or word prediction not working.

Looking at the "insights" it doesn't look like anything is happening.

So is OpenBoard still under devellopment?

**Comment by UserX404** [comment]
Duplicate of #211

**Comment by Glitchy-Tozier** [comment]
It's not a duplicate, the german thing was just a remark.

Please read the title of the issue and/or the whole text.

Thanks for taking the effort and replying though  :)

**Comment by AlanSanchezP** [comment]
I can almost bet that dslul is busy in his job or something else, and come back to work on openboard as soon as he can.

After all, there was a huge inactive period between January and September this year, after which we got quite a few updates :)

**Comment by naDevi** [comment]
@Glitchy-Tozier @AlanSanchezP 
If you know and have free then can you tell me instruction about how to add new keyboard (non-exist keyboard on this app).. only keyboard... idk about dictionaries (hard to find)

In this case, you can point me specific(prefer) existing keyboard source parts on this repo then i can follow it and do the same then PR

**Comment by Glitchy-Tozier** [comment]
I have no idea, unfortunately.

**Comment by dslul** [comment]
@Glitchy-Tozier sorry I don't remember, why is prediction not working?

**Comment by Glitchy-Tozier** [comment]
@dslul  I haven't used OpenBoard for some time and am not sure what was wrong with the prediction.
