### ISSUE TITLE
Feature Request: Back space long press deletes whole word

### ISSUE THREAD

**Issue by utzer** [dslul/openboard#255]
I would love a function that deletes a whole word when backspace is pressed for a longer duration, so the deletion should switch from letter wise to word wise.

**Comment by slaecker** [comment]
I second that but configurable so it can be switched off by the user and the kick-in duration can also be set.

**Comment by jnnkB** [comment]
This seems to be a duplicate of https://github.com/dslul/openboard/issues/28
