### ISSUE TITLE
Add Size settings to keyboard

### ISSUE THREAD

**Issue by sprainbrains** [dslul/openboard#26]
Really, Relly nice keybord for FOSS-devices.
But i can't change keyboard side for my big fingers(
Do you can add this feature in the future releases?

**Comment by dslul** [comment]
It was already implemented in version 1.1, we need to wait for F-Droid to build it.

**Comment by sprainbrains** [comment]
> It was already implemented in version 1.1, we need to wait for F-Droid to build it.

oh really? Thanks.
Wait FD-Droid
