### ISSUE TITLE
Could someone fix the Linux build instructions?

### ISSUE THREAD

**Issue by trurebel** [dslul/openboard#262]
Hi folks, I saw the commandline instructions mentioning pacman on the front page, and I thought Archlinux, what can go wrong. Well, I applied them in Manjaro, got /snap/androidsdk/current as the path and androidsdk as an alias (I believe) of sdkmanager, then my first invocation of gradle complains of licenses, androidsdk --licenses fixes some licenses it seems but not

` Configure project :app
WARNING: Compatible side by side NDK version was not found for android.ndkVersion '21.3.6528147'
Compatible side by side NDK version was not found for android.ndkVersion '21.3.6528147'
Checking the license for package SDK Patch Applier v4 in /snap/androidsdk/current/licenses
Warning: License for package SDK Patch Applier v4 not accepted.
Checking the license for package NDK (Side by side) 21.3.6528147 in /snap/androidsdk/current/licenses
Warning: License for package NDK (Side by side) 21.3.6528147 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.sdk.LicenceNotAcceptedException: Failed to install the following Android SDK packages as some licences have not been accepted.
     ndk;21.3.6528147 NDK (Side by side) 21.3.6528147
     patcher;v4 SDK Patch Applier v4
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
`

I am intrigued particularly by this patcher license, anyway stuck around here, despite installing ndk-bundle and rerunning --licenses etc, not sure what the next step might be.

**Comment by dslul** [comment]
If it's not a problem, you can download android studio, import the project and compile, that's what I usually do. Or, you can accept the sdk license by doing as suggested [here](https://stackoverflow.com/questions/54273412/failed-to-install-the-following-android-sdk-packages-as-some-licences-have-not).

**Comment by ErinTheSmall** [comment]
ran into exactly the same errors myself, the suggested --licenses does not help, it insists that all licenses are already agreed

**Comment by TheCrowned** [comment]
I can confirm using Android Studio fixes the license issue. One can download and run Android Studio, it will set up whatever it needs in `~/.android-sdk`, and then you can go back using the terminal and ditch the gigantic IDE beast if you don't want it. Licenses problem seems fixed after having opened Studio once.
