### ISSUE TITLE
what is aosp?

### ISSUE THREAD

**Issue by markfirmware** [dslul/openboard#265]
github suggested this repo, aosp in the description, but aosp not defined in readme

    gitpod /workspace/openboard $ grep -i aosp README.md 
    100% FOSS keyboard, based on AOSP.
    You can use [this tool](https://github.com/remi0s/aosp-dictionary-tools) to create a dictionary. You need a wordlist, as described [here](https://github.com/dslul/openboard/blob/master/dictionaries/sample.combined). The output .dict file must be put in [res/raw](https://github.com/dslul/openboard/tree/master/app/src/main/res/raw).
    - [AOSP Keyboard](https://android.googlesource.com/platform/packages/inputmethods/LatinIME/)

**Comment by NoahAndrews** [comment]
AOSP stands for Android Open Source Project, which is the version of Android without any manufacturer customizations or proprietary Google code.

OpenBoard is based on the keyboard included with AOSP, which is not the same thing as GBoard (it's far more limited in functionality).

**Comment by markfirmware** [comment]
Thank you! I suggest adding that in the front of the readme, and to be complete, add a definition for foss. I will close this and leave that to your discretion. Thanks for the quick response.

**Comment by NoahAndrews** [comment]
I would if I was the maintainer :)
