### ISSUE TITLE
Feature request: ctrl button 

### ISSUE THREAD

**Issue by nahuhh** [dslul/openboard#272]
Use case 
Ctrl + a,v,c,x,z,y etc for select all etc 
[20210118_112542.jpg](https://user-images.githubusercontent.com/50635951/104943165-51a09b80-5983-11eb-8633-7bc28a56e2c8.jpg)

**Comment by mainmachine** [comment]
Also for ssh commands, for instance ctrl+d to exit session, ctrl+r for bash history, etc.

Lack of this key means I cannot use openboard as a primary keyboard.

**Comment by jnnkB** [comment]
Is this a duplicate of https://github.com/dslul/openboard/issues/84 ?
