### ISSUE TITLE
Better emoji sorting

### ISSUE THREAD

**Issue by Hogerys** [dslul/openboard#282]
If i would like to select an amoji sometimes i just have to scroll through many versions of one emoji. For examples emoticons with different skin tones are all listed. It would be better to make these into one button per category and with a long press and holding you could select one out of the list. It could also remember the which one you choose. This could be toggled in a setting.

![IMG_20210127_174948](https://user-images.githubusercontent.com/74684948/106024430-13fcea80-60c8-11eb-8a55-7803ffb39a34.jpg)

**Comment by MajeurAndroid** [comment]
This is already fixed and will be available in next release I guess.
See #242
