### ISSUE TITLE
Change Order in German Layout?

### ISSUE THREAD

**Issue by maf-o** [dslul/openboard#314]
May it be possible to change the order in German QWERTZ Layout
![ChangeOrder](https://user-images.githubusercontent.com/60689016/109841636-8887f380-7c49-11eb-88b6-cd1d3e6cb43e.jpg)

**Comment by UserX404** [comment]
Duplicate  of https://github.com/dslul/openboard/issues/211
Already fixed by https://github.com/dslul/openboard/commit/ec55fc09aa02d968274f50a690aa4d99a7520859

But there has been no new public release since Oct20 [v1.4.2](https://github.com/dslul/openboard/releases/tag/v1.4.2) 😞
