### ISSUE TITLE
Add Workman Layout

### ISSUE THREAD

**Issue by Pentaphon** [dslul/openboard#316]
Wondering if it's possible to add the Workman Layout as shown here. 

https://workmanlayout.org/

As you can see, Simple Keyboard recently added it. 

https://github.com/rkkr/simple-keyboard/pull/249

**Comment by toniz4** [comment]
Is is, i opened #296 adding the colemak DH layout, it would be simple to add new layouts.

**Comment by AverytheFurry** [comment]
Would be great, I use workman too.

**Comment by jnnkB** [comment]
In #320 @Damjan94 started converting the QUERTY layout to Workman: https://github.com/dslul/openboard/issues/320#issuecomment-812746324

**Comment by Damjan94** [comment]
Thanks for reminding me. Just created a [pull request](https://github.com/dslul/openboard/pull/433)
