### ISSUE TITLE
Categorizing issues

### ISSUE THREAD

**Issue by jnnkB** [dslul/openboard#318]
Hi,

I tried to create an overview of all currently open issues. I tried to categorize them and find duplicates. I'm not trying to put any pressure an anyone I just wanted to try to help and organize these issues.

## Bugs

Keyboard not sending KEYCODE_DEL on backspace #331

Always Show Number Row doesn't work for colemak mod-dh #328

Issue with welcome screen not showing "Get started" button https://github.com/dslul/openboard/issues/303

Glitch when editing Firefox URL https://github.com/dslul/openboard/issues/293

Crashes due to having no code for numpad https://github.com/dslul/openboard/issues/279

No autocorrect or suggestions in Simplenote app https://github.com/dslul/openboard/issues/275

number row not working on samsung tab a 8.4 https://github.com/dslul/openboard/issues/273

linux build instructions not working https://github.com/dslul/openboard/issues/262

Crash when using with TalkBack https://github.com/dslul/openboard/issues/260

The shrug ASCII emoji should only require a single key press https://github.com/dslul/openboard/issues/251

Word prediction does not work with TextInputEditText https://github.com/dslul/openboard/issues/247

"Always show number row" doesn't work for English (US) (Dvorak) https://github.com/dslul/openboard/issues/244

double space glitch https://github.com/dslul/openboard/issues/238

No learning of typed words https://github.com/dslul/openboard/issues/233

spacebar swipe navigation functionality in Termux https://github.com/dslul/openboard/issues/227

Additional leading space is inserted when correcting autocorrect after using backspace https://github.com/dslul/openboard/issues/222

Incognito tab can't work https://github.com/dslul/openboard/issues/215

Display Error when just numbers are allowed https://github.com/dslul/openboard/issues/213

Invert space swipe  for RTL languages https://github.com/dslul/openboard/issues/205

OpenBoard IME replaced by default IME after reboot if installed on external storage https://github.com/dslul/openboard/issues/203

Can't begin app configuration https://github.com/dslul/openboard/issues/196

Emojis cannot be inserted when accessed by long pressing the enter key. https://github.com/dslul/openboard/issues/184

Numeric layout not showing up on tablet https://github.com/dslul/openboard/issues/176

Resources$NotFoundException https://github.com/dslul/openboard/issues/175

Keyboard doesnt sit flush with bottom of display https://github.com/dslul/openboard/issues/165

Bug Delete/back button isn't working https://github.com/dslul/openboard/issues/164

Back button form app interface is not working. https://github.com/dslul/openboard/issues/156

Occasionally the keyboard stops working and the app needs reopening.              https://github.com/dslul/openboard/issues/152

Add input style icon almost invisible https://github.com/dslul/openboard/issues/135

Dictionary shortcut doesn't work with special characters https://github.com/dslul/openboard/issues/122

Swiping over Spacebar Freezes Cursor https://github.com/dslul/openboard/issues/67

General fluency and word prediction https://github.com/dslul/openboard/issues/63

missing enter button https://github.com/dslul/openboard/issues/52

## Improvements

Needs Large Size Search/Enter Key in AMOLED Black Theme https://github.com/dslul/openboard/issues/319

shift the number row along with rest of board https://github.com/dslul/openboard/issues/317

Delete entries in autocorrection https://github.com/dslul/openboard/issues/313

Disable autocorrect when typing in email fields https://github.com/dslul/openboard/issues/312

if their are no recent emojis, show a message https://github.com/dslul/openboard/issues/302

Unwanted Behaviour: Space Bar cursor movement https://github.com/dslul/openboard/issues/280

change emoji type using scroll left or right https://github.com/dslul/openboard/issues/257

Enable white navigation bar https://github.com/dslul/openboard/issues/253

Comma should add space https://github.com/dslul/openboard/issues/252

better word prediction https://github.com/dslul/openboard/issues/246

better URL suggestion https://github.com/dslul/openboard/issues/218

back button on emoji screen should only close emoji screen https://github.com/dslul/openboard/issues/193

Change secondary keys of qwertz/qwerty keyboard row when number row is enabled https://github.com/dslul/openboard/issues/189

Proper minus sign in long-tap symbols https://github.com/dslul/openboard/issues/177

Keyboard vibrations should be muted if ringer is set to silent https://github.com/dslul/openboard/issues/147

Reduce size of package https://github.com/dslul/openboard/issues/47

Improve suggestions https://github.com/dslul/openboard/issues/43

Add Setting: Automatic space insertion after word suggestion selection https://github.com/dslul/openboard/issues/14

Word suggestion disappears after completing the word https://github.com/dslul/openboard/issues/11

## Feature Requests

Abbreviation expander https://github.com/dslul/openboard/issues/311

Unlimited Number of Clip Board Manager https://github.com/dslul/openboard/issues/235

Speak typed keys using Mozilla TTS https://github.com/dslul/openboard/issues/235

use  center prediction on clicking space https://github.com/dslul/openboard/issues/306

copy tool https://github.com/dslul/openboard/issues/301

Option to add a space after selecting a suggested word https://github.com/dslul/openboard/issues/295

Handwriting/stylus support https://github.com/dslul/openboard/issues/288

Ability to enter pin code with open board https://github.com/dslul/openboard/issues/287

"rebuild emoji selector from telegram api or other sources" https://github.com/dslul/openboard/issues/287

Disable spell checking on address bar on browsers https://github.com/dslul/openboard/issues/286

Smooth scrolling on emojis https://github.com/dslul/openboard/issues/285

Back space long press deletes whole word https://github.com/dslul/openboard/issues/28

Swipe/Glide to text https://github.com/dslul/openboard/issues/3

Choose emoji skin color in settings https://github.com/dslul/openboard/issues/268

Make a word start with a capital letter from the end of the word by shift key https://github.com/dslul/openboard/issues/141

Adjust the keyboard mode https://github.com/dslul/openboard/issues/245

hide the special characters from the keys https://github.com/dslul/openboard/issues/194

floating mode https://github.com/dslul/openboard/issues/229

transliteration from english to Hindi while typing https://github.com/dslul/openboard/issues/224

Number Pad https://github.com/dslul/openboard/issues/221

add dictionaries from the application https://github.com/dslul/openboard/issues/219

new gestures https://github.com/dslul/openboard/issues/217

Settings Backup https://github.com/dslul/openboard/issues/214

Text correction suggestions for physical keyboard https://github.com/dslul/openboard/issues/201

Disable long press from space https://github.com/dslul/openboard/issues/198

Search for Emojis https://github.com/dslul/openboard/issues/197 https://github.com/dslul/openboard/issues/35

copy and paste buttons on long pressed enter https://github.com/dslul/openboard/issues/193

change emojis https://github.com/dslul/openboard/issues/193

Add version-information to the app https://github.com/dslul/openboard/issues/181

Let OpenBoard colors change in accordance to app-colors https://github.com/dslul/openboard/issues/180

test text field where the themes are being selected https://github.com/dslul/openboard/issues/174

Voice Typing https://github.com/dslul/openboard/issues/169

Multi-language dictionary on same keyboard https://github.com/dslul/openboard/issues/7

Option to modify long-pressed symbol pop-ups https://github.com/dslul/openboard/issues/154

custom theme color https://github.com/dslul/openboard/issues/124

Delete learned words https://github.com/dslul/openboard/issues/106

Text selection https://github.com/dslul/openboard/issues/73

Clipboard (cut/copy/paste) functionality https://github.com/dslul/openboard/issues/60 https://github.com/dslul/openboard/issues/16

export/import of personal dictionary https://github.com/dslul/openboard/issues/59

Option to have a most recently used section for emojis https://github.com/dslul/openboard/issues/55

Long-press vibration feedback https://github.com/dslul/openboard/issues/53

Show suggestions after typing or selecting a word https://github.com/dslul/openboard/issues/42

Disable key pop-up when entering password/during login https://github.com/dslul/openboard/issues/29

one hand mode https://github.com/dslul/openboard/issues/13

Allow blacklisting of words from default dictionary https://github.com/dslul/openboard/issues/5

Allow setting the background colour https://github.com/dslul/openboard/issues/1

Resize Split Keyboard Width https://github.com/dslul/openboard/issues/322

[Feature Request] Gesture to enable/disable split keyboard https://github.com/dslul/openboard/issues/324

## Themes

Amoled Material Dark Border https://github.com/dslul/openboard/issues/290

Xperia Skin https://github.com/dslul/openboard/issues/9

### New Layouts

Workman https://github.com/dslul/openboard/issues/316

ABC-9 https://github.com/dslul/openboard/issues/310

Arabic keyboard with Arabic numerals https://github.com/dslul/openboard/issues/298

Phonetic Cyrillic Layout https://github.com/dslul/openboard/issues/266

Japanese https://github.com/dslul/openboard/issues/239

Neo Keyboard https://github.com/dslul/openboard/issues/226

BÉPO keyboard layout https://github.com/dslul/openboard/issues/209

Telex input method (Vietnamese) https://github.com/dslul/openboard/issues/206 (in the comments)

Chinese https://github.com/dslul/openboard/issues/192

Japanese https://github.com/dslul/openboard/issues/192

Tamazight https://github.com/dslul/openboard/issues/103

Turkish F layout https://github.com/dslul/openboard/issues/72

General https://github.com/dslul/openboard/issues/31

Korean https://github.com/dslul/openboard/issues/24

VNI (Vietnamese) https://github.com/dslul/openboard/issues/321

### Improvements

Missing buttons in Turkish QWERTY https://github.com/dslul/openboard/issues/309

Remove latin letter "S" in Serbian Cyrillic keyboard! https://github.com/dslul/openboard/issues/299

Option to turn on accented letters https://github.com/dslul/openboard/issues/292

The language of the spell checker cannot be switched with the keyboard language https://github.com/dslul/openboard/issues/258

Ruble sign for Russian layout https://github.com/dslul/openboard/issues/210

qwerty settings for others languages https://github.com/dslul/openboard/issues/188 

german layout option to choose numbers as first alternative https://github.com/dslul/openboard/issues/79

T9 keyboard layout remains english when switching to another language https://github.com/dslul/openboard/issues/78

### Bugs

German Layout "ß" should be the first option https://github.com/dslul/openboard/issues/211 

Vietnamese Layout "â" and "ă" should be first options https://github.com/dslul/openboard/issues/206

Wrong # character on cyrillic (Russian) layout. It should read № instead. https://github.com/dslul/openboard/issues/155

improve special symbols polish layout https://github.com/dslul/openboard/issues/148

improve special symbols Spanish layout https://github.com/dslul/openboard/issues/142 (maybe this is already fixed)

Greek Ω and μ are missing https://github.com/dslul/openboard/issues/115

### New Dictionaries

Bangla https://github.com/dslul/openboard/issues/234

Hungarian https://github.com/dslul/openboard/issues/128

General https://github.com/dslul/openboard/issues/31

Korean https://github.com/dslul/openboard/issues/24

### Bugs

Swedish dictionary doesn't work https://github.com/dslul/openboard/issues/225

## Add Emojis

ᕙ(  • ‿ •  )ᕗ https://github.com/dslul/openboard/issues/297

🥱🥺 https://github.com/dslul/openboard/issues/294

🏳️‍⚧️ Lgbt flags missing from emoji keyboard https://github.com/dslul/openboard/issues/326

## Add Keys

Tab key https://github.com/dslul/openboard/issues/284

alt and shift backspace modifiers https://github.com/dslul/openboard/issues/274

ctrl https://github.com/dslul/openboard/issues/84

cursor keys https://github.com/dslul/openboard/issues/267

## Meta

Is OpenBoard still being developed? https://github.com/dslul/openboard/issues/250

Add Changelog for most Recent Version in F-Droid. https://github.com/dslul/openboard/issues/171

Github Sponsors https://github.com/dslul/openboard/issues/160

Add Liberapay donation possibility https://github.com/dslul/openboard/issues/149

Update based on LineageOS changes https://github.com/dslul/openboard/issues/109

name "freeboard" https://github.com/dslul/openboard/issues/95

translation https://github.com/dslul/openboard/issues/74

Adding keyboard layouts from AOSP possible? #332

## Questions

How to turn off incognito mode? https://github.com/dslul/openboard/issues/249

## possible duplicates and already fixed issues

https://github.com/dslul/openboard/issues/307 of https://github.com/dslul/openboard/issues/235
https://github.com/dslul/openboard/issues/320
https://github.com/dslul/openboard/issues/75
https://github.com/dslul/openboard/issues/354

---

Since these are relatively many issues I would suggest to

1. Use projects and labels to sort these issues
2. close duplicates and already fixed issues
3. Perhaps add a issue template stating to only report one issue/make one feature request per issue
4. Sort these issues by importance and practicability

If you don't have any time to do any of this feel free to simply ignore this issue.

Kind regards

**Note:** The distinction between improvements and features isn't a really clear one. Many could also belong into the other category.

**Comment by dslul** [comment]
Thanks a lot for the effort! I closed some duplicate issues you listed, the backlog is starting to become a bit scary for one man alone...

**Comment by jnnkB** [comment]
Thanks for closing them. I updated the issue. If you have any idea how I could support you in keeping these issues organized feel free to ask.

**Comment by AverytheFurry** [comment]
> Thanks a lot for the effort! I closed some duplicate issues you listed, the backlog is starting to become a bit scary for one man alone...

Damn i wish i was good at programming so i could help

**Comment by jnnkB** [comment]
Closing in favor of labels
