### ISSUE TITLE
Add spacebar trackpad feature

### ISSUE THREAD

**Issue by Mhowser** [dslul/openboard#32]
With Gboard users can use the spacebar as a "trackpad" to move the cursor around the text.

**Comment by dslul** [comment]
Already implemented in version 1.2.

**Comment by Mhowser** [comment]
Ah thanks, I got the app from f-droid and they haven't updated to 1.2 yet. 
Cheers!

**Comment by dslul** [comment]
@Mhowser just a curiosity, does gboard implement also vertical movements (like iOS does) or just left and right?

**Comment by Mhowser** [comment]
Just left and right tracking, if I needed to go up and down I would just
use my finger to tap on the spot where I want to go.
