### ISSUE TITLE
Lgbt flags missing from emoji keyboard

### ISSUE THREAD

**Issue by AverytheFurry** [dslul/openboard#326]
Hey, as the title says, lgbt flags seem to be missing from the emoji keyboard.

**Comment by GlenMerlin** [comment]
Typing this using openboard ️‍🏳️‍🌈🏳️‍⚧️ and these seem to be working on 1.4.3

**Comment by AverytheFurry** [comment]
F-droid is not yet updated to that ver. Will check again later.

**Comment by dslul** [comment]
Already fixed.
