### ISSUE TITLE
Please publish the apk file here on GitHub

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [dslul/openboard#33]
Hello first of all thank you for the great app. Please continue and don't give up. Many open source Android keyboards are dead for years.

Now there is finally an app again and hope it stays that way. Hope you will not leave us or switch to SwiftKey or other because of new employers.

When you release a new version. Can you add the apk file under GitHub releases? 
https://github.com/dslul/openboard/releases

I don't use Google Play Store and F-droid is very slow with recent updates.

**Comment by dslul** [comment]
Will do, starting from 1.3

**Comment by dslul** [comment]
done, I uploaded the apk in the release tab

**Comment by USB3-2-10Gbit** [comment]
Thank.
Can you add the version number and name.

I download apk file very often and I don't like to change the name to the app name and version number again.

That's it: OpenBoard_1.3.apk
------

Other question I have deleted the old F-droid version because an update from version 1.0 (F-Droid) to 1.3 GitHub did not work. The update is not installed.

I found another problem when I deleted the F-Droid version and first downloaded and installed the apk file from GitHub. There was no OpenBoard icon on the Android homescreen. Normal or bug?

I have an Android 9 phone.

**Comment by dslul** [comment]
You cannot update from the F-Droid version because signatures are different. This apk and the playstore version have my own signature. Regarding the icon, there is a toggle in settings, do you have it enabled?

**Comment by USB3-2-10Gbit** [comment]
The toggle in OpenBoard settings for app icon is very probably disabled.

When I try to press the comma key for a long time to reach OpenBoard settings this way. It doesn't work I can't get back to OpenBoard settings. 

I do not want to reinstall the app can you reproduce the problem?

**Comment by jwsp1** [comment]
> You cannot update from the F-Droid version because signatures are different. This apk and the playstore version have my own signature. Regarding the icon, there is a toggle in settings, do you have it enabled?

IMO, the toggle for the icon should be enabled by default

**Comment by dslul** [comment]
> The toggle in OpenBoard settings for app icon is very probably disabled.
> 
> When I try to press the comma key for a long time to reach OpenBoard settings this way. It doesn't work I can't get back to OpenBoard settings.
> 
> I do not want to reinstall the app can you reproduce the problem?

what version are you using? 1.2 had a bug on some devices when trying to open settings.

**Comment by USB3-2-10Gbit** [comment]
> > The toggle in OpenBoard settings for app icon is very probably disabled.
> > When I try to press the comma key for a long time to reach OpenBoard settings this way. It doesn't work I can't get back to OpenBoard settings.
> > I do not want to reinstall the app can you reproduce the problem?
> 
> what version are you using? 1.2 had a bug on some devices when trying to open settings.

OpenBoard 1.3 (apk file from GitHub). Device is Xiaomi Redmi Note 8 (Android 9)

**Comment by USB3-2-10Gbit** [comment]
@dslul 
I found the cause.

it only appears in MIUI and probably other Android systems that do something similar.

Here's the link.
https://stackoverflow.com/questions/56295901/miui-permission-denied-activity-keyguardlocked

Can you fix it? 

you have to give direct instructions so that other MIUI users know exactly what to activate.

In my case on MIUI 11 (Android 9)


1. Settings -> Apps -> Manage apps -> OpenBoard -> Other permissions
2. Activate this here: 

Display pop-up windows while running in background

**Comment by jwsp1** [comment]
> @dslul
> I found the cause.
> 
> it only appears in MIUI and probably other Android systems that do something similar.
> 
> Here's the link.
> https://stackoverflow.com/questions/56295901/miui-permission-denied-activity-keyguardlocked
> 
> Can you fix it?
> 
> you have to give direct instructions so that other MIUI users know exactly what to activate.
> 
> In my case on MIUI 11 (Android 9)
> 
> 1. Settings -> Apps -> Manage apps -> OpenBoard -> Other permissions
> 2. Activate this here:
> 
> Display pop-up windows while running in background

What about displaying a toast 'in case nothing happens, please open the app from app drawer'? It's obviously just a minority of users who face this issue and the easiest way is to open openboard manually then. But indeed, maybe @dslul can write device specific issues/notes in Readme file for users who don't care changing some device settings.

**Comment by dslul** [comment]
@USB3-2-10Gbit can you open a new issue for this problem? It can get lost here otherwise.
