### ISSUE TITLE
[BUG] Emojis' skin colours are all over the place

### ISSUE THREAD

**Issue by fiva67** [dslul/openboard#330]
Emojis' skin colours appear all over the place and its very difficult and time consuming to reach the last emojis, because of this. This is how they appear: 
![Screenshot_20210402_133245](https://user-images.githubusercontent.com/80595316/113442692-32999d80-93f9-11eb-9608-8561b1a5b090.jpg)

Whereas the emojis of the same phone appear like this in Microsoft swift key keyboard and it's much preferable.
![Screenshot_20210402_211522](https://user-images.githubusercontent.com/80595316/113442892-902dea00-93f9-11eb-975a-6f7858e77668.jpg)

**Comment by jnnkB** [comment]
Duplicate of #6 and already fixed. But it's not included in any release yet.

**Comment by fiva67** [comment]
Alright then, I' m going to close the issue.
