### ISSUE TITLE
Many languages keyboards do not exist

### ISSUE THREAD

**Issue by IniUe** [dslul/openboard#332]
Said in title, and i'm not so clear about this issue. If particular languages keyboards do not exist on device built-in stock ROM AOSP keyboard then it means it doesn't available for openboard too? then in this case it can vary for android version and etc.

If it so can't you bring keyboards from latest android version (and old versions, if has discontinued keyboards) and make this app as the collection of keyboards (foss app)? @dslul 

Meanwhile, it seems this project maintainers quite busy and i noticed @jnnkB categorizing issues and may open to talk. Do you or other have knowledge about above mentioned issue? if then drop a comment

**Comment by IniUe** [comment]
https://github.com/dslul/openboard/issues/318

**Comment by jnnkB** [comment]
As far as I understand it this projekct is based on AOSP in the way that the source code from AOSP was modified an became openboard. Therefore I think the available keyboard layout depend on the openboard version an not the OS version. Therefore adding keyboards from AOSP might be possible if they still use the same file format.

**Comment by IniUe** [comment]
> As far as I understand it this projekct is based on AOSP in the way that the source code from AOSP was modified an became openboard. Therefore I think the available keyboard layout depend on the openboard version an not the OS version. Therefore adding keyboards from AOSP might be possible if they still use the same file format.

Okey, so openboard has many releases in 2020 (it equal to android pie, android 10, android 11) but openboard only has 41 languages keyboard (that available same amount of device os aosp keyboard). in this case, it doesn't has needed languages keyboards so i still depend on proprietary keyboard found on gstore

**Comment by IniUe** [comment]
I know as a single person @dslul maintain this project, i prefer ask you to add all available writing systems keyboards when you find some enough time to work for openboard instead fix bugs or do other enhancements then at first-place everyone can use this foss board

**Comment by dslul** [comment]
@IniUe this should include every layout that is in aosp, but if you're aware of some that aren't tell me, I can add them.

**Comment by IniUe** [comment]
filipino/tagalog (philippines), dhivehi (maldives), malaysian (malaysia) - not sure if those has on android; couldn't check

I see something i've already misunderstood; above comment mentioned all input method available in gboard but that's about aosp keyboard

**Comment by itsnotsaved** [comment]
how long will take to implement? or are you already working on this?

**Comment by jnnkB** [comment]
@IniUe I tried to find these input methods in the AOSP Keyboard source, but unfortunately I wasn't able to find them. This is the URL where I looked: https://cs.android.com/android/platform/superproject/+/master:packages/inputmethods/LatinIME/java/res/xml/ Where did you find them? On the version of the keyboard on your device?

**Comment by IniUe** [comment]
@jnnkB sorry for delay reply and for that, I didn't checked the source code; before find about third-party keyboard apps, i tried to update aosp keyboard to newer version then i found https://www.apkmirror.com/apk/lineageos/android-keyboard-aosp-2/android-keyboard-aosp-2-11-release/android-keyboard-aosp-11-2-android-apk-download/ (i noticed details about mentioned languages in the description below to version: 11:28) and even that apk get installed successfully but aosp remain on pre-installed version)

Furthermore, i have seen latest android versions contain phone users don't depend on third-party keyboards for some known languages (either aosp or gboard); but i have not checked their devices especially to see which and versions (aosp or gboard)

However i really wonder if that all mentioned input methods still don't exist on that most popular mobile os, android.

**Comment by jnnkB** [comment]
Ah ok. [LineageOS/android_packages_inputmethods_LatinIME ](https://github.com/LineageOS/android_packages_inputmethods_LatinIME) (probably) is the source of that APK. For most of the languages you send, I didn't found a keyboard layout in that repo either. The ones I found with a keyboard layout also exists in openboard. Most of the other ones seem to only include translations of the Keyboard texts and are using a querty layout.

**Comment by IniUe** [comment]
So that release note had misled me 😅 
Meanwhile, i installed gboard to check; it has that all required keyboards and more but it seems doesn't consider to provide for aosp.

**Comment by jnnkB** [comment]
I'm closing this issue since it seems that AOSP keyboard does not support these languages either. Therefore they'll have to be added manually.
