### ISSUE TITLE
[Enhancement?] Remove microphone icon from keyboard

### ISSUE THREAD

**Issue by TheSilencedOne** [dslul/openboard#333]
I would like to have the microphone icon removed from the keyboard as it doesn't do anything (i Don't want text to speech support just want the microphone icon to be removed) also maybe have a option to remove incognito mode icon.
![Screenshot_20210408-224946_1_1](https://user-images.githubusercontent.com/78061111/114121914-43488880-98bd-11eb-967b-baaf42feb31b.png)

**Comment by dslul** [comment]
Well, there is already a toggle to do that :)

**Comment by TheSilencedOne** [comment]
> Well, there is already a toggle to do that :)

Can you please tell me where this option is becuase i cant seem to find it

**Comment by dslul** [comment]
> Can you please tell me where this option is becuase i cant seem to find it

under preferences - the last toggle
