### ISSUE TITLE
[Feature suggestion] Vibration intensity

### ISSUE THREAD

**Issue by riccardo1991** [dslul/openboard#337]
Hello, I am using openboard for a couple of week and it's perfect for my daily use.
A nice feature would be the possibility to set the vibration duration/intensity, e.g. as SimpleBoard [here](https://github.com/rkkr/simple-keyboard/blob/1cba0210215aeb143f5da1d5bcf6ee82bcf3e06a/app/src/main/java/rkr/simplekeyboard/inputmethod/latin/settings/Settings.java#L223-L226).

Best regards

**Comment by dslul** [comment]
Hi, that feature is already implemented https://github.com/dslul/openboard/blob/master/app/src/main/java/org/dslul/openboard/inputmethod/latin/settings/Settings.java#L311
We share the same aosp codebase, the code is pretty similar.

**Comment by riccardo1991** [comment]
Sorry, definetly my fault, I didn't saw it was uder advanced settings and not close to the "toggle vibration".
Thank you!
