### ISSUE TITLE
[Feature Request] add a clipboard 

### ISSUE THREAD

**Issue by murph2495** [dslul/openboard#338]
it would be nice and it would be really useful to add a clipboard of

**Comment by Offerel** [comment]
AT least in Gboard there is an option to switch to a "Clipboard View". You have copy&paste buttons there and arrow buttons to navigate the cursor up/down/left/right. This would be the killer feature for me. It must not be a 1:1 copy of Gboard but a similar thinbg would be really nice.

**Comment by swarupbhanjachowdhury** [comment]
Yes I miss that feature, please devs try to find a solution

**Comment by jnnkB** [comment]
Is this a duplicate of #60 or do you imagine something different?

**Comment by Offerel** [comment]
At least for me, that's the same. Haven't just notified #60

**Comment by jnnkB** [comment]
Then I'm closing this as a duplicate of #60
