### ISSUE TITLE
Enable to run on boot.

### ISSUE THREAD

**Issue by karnotcycle** [dslul/openboard#354]
**Is your feature request related to a problem? Please describe.**

Yes, The keyboard doesn't work until unlocked after boot. Simple keyboard on the other hand runs on boot without unlocking required.

**Describe the solution you'd like**

Honestly this one option is keeping me from using it full fledged.

**Describe alternatives you've considered**
Using simple keyboard just for unlocking.

They are even happy for you to copy the feature : here's a reply from them - "File an issue for OpenBoard. They are welcome to copy daae07b."

**Comment by jnnkB** [comment]
I think this is a duplicate of https://github.com/dslul/openboard/issues/75 and already fixed in https://github.com/dslul/openboard/pull/346

**Comment by TheCrowned** [comment]
> Does it mean It will get fixed in the next release?
Yes
