### ISSUE TITLE
Matrix community broken and room unjoinable

### ISSUE THREAD

**Issue by calvinrw** [dslul/openboard#360]
**Describe the bug**

The Matrix community in the README file for dslul/openboard is broken, and the 'general' room is unjoinable.

**To Reproduce**
1. Open the README file, be it in a web browser or text editor
2. Navigate to the Matrix.to link
3. Attempt to open the community link in a Matrix client, or copy and paste the community handle into a client.
4. See error "No known servers" when attempting to join the 'general' room.

**Expected behavior**
A Matrix room that is configured correctly can be joined by people who wish to join.

**Screenshots**
Not applicable.

**Smartphone (please complete the following information):**
Not applicable; affects desktop and smartphone clients equally.

**Additional context**
I originally wanted to hop on Matrix to air my grievances about changes to the AMOLED black theme in release 1.4.3, but I guess I'll open PRs and actually fix the things that bother me instead.

Matrix communities were never fully functional or well thought-through, and will soon be deprecated in favor of upcoming Matrix spaces. In the meantime, I strongly recommend creating a room alias for the 'general' room, and sharing that link in the README instead.

**Comment by dslul** [comment]
Sorry, I'm new to matrix, I thought communities were similar to discord. Can you check now?

**Comment by calvinrw** [comment]
I can confirm the link works now, and I can join #openboard:matrix.org without any issues. Thanks for addressing this, and for helping support and promote Matrix!
