### ISSUE TITLE
play protect

### ISSUE THREAD

**Issue by ocaeon** [dslul/openboard#363]
not sure if this should go here but thought it worthwhile mentioning.  tried installing version 1.2.2 of this through fdroid, and it triggers the g**g's 'play protect' function.  i guess they just got annoyed with bug reports spilling over on them?

**Comment by dslul** [comment]
> not sure if this should go here but thought it worthwhile mentioning. tried installing version 1.2.2 of this through fdroid, and it triggers the g**g's 'play protect' function.

Does it prevent you from installing the app, meaning it detects it as malware?

> i guess they just got annoyed with bug reports spilling over on them?

With 'they' you are referring to google? what bug reports?

**Comment by SrEstegosaurio** [comment]
Play Protect does not stop you if you want to install an app. Just warns you because it **CAN** be dangerous. But you can install it anyway and just use it.
