### ISSUE TITLE
Esperanto layout

### ISSUE THREAD

**Issue by victorbnl** [dslul/openboard#366]
![Screenshot_20210520-132340_Notally](https://user-images.githubusercontent.com/39555268/118970544-a6264880-b96e-11eb-8048-36a803f6498f.png)

It exists on AOSP keyboard

**Comment by mrshll1001** [comment]
It exists in OpenBoard as well, enable it in "languages" via the OpenBoard settings.

![photo_2021-07-16_09-35-52](https://user-images.githubusercontent.com/2675224/125918672-81f1888e-6657-4cf3-9630-820f35096f25.jpg)
![photo_2021-07-16_09-35-54](https://user-images.githubusercontent.com/2675224/125918675-ddfec946-9d50-4569-a50f-432271657651.jpg)

**Comment by victorbnl** [comment]
Oh ok perfect! I think Esperanto wasn't in the languages when I made the issue
