### ISSUE TITLE
[REQUEST] Greek Dictionary 🙏 

### ISSUE THREAD

**Issue by wuxetim** [dslul/openboard#38]
Hello there, thank you for all your hard work with OpenBoard!

It seems to be the best FOSS available keyboard up on Fdroid. It is a shame Fdroid takes so long to publish the updates though.

I see a lot of open issues requesting language dictionaries so I am adding my own request for Greek dictionary. I am assuming it makes sense to add all requested languages if it does not make the application too large. Allowing the user to download desired dictionaries via a temporary internet access during initial setup might be something to consider. What do you think?

Also wanted to ask if Asian languages or languages with other alphabets such as Japanese, Korean and Arabic can be supported. They do not appear under input methods so do they need a different approach?

Thank you very much and keep up the good work.

**Comment by dslul** [comment]
Hi, I'm using aosp [wordlists](https://github.com/dslul/openboard/tree/master/dictionaries) and greek is missing. If someone is willing to assemble (and test) one, I'll gladly add it to the codebase.

**Comment by irowea** [comment]
@wuxetim Thanks for opening a request for Greek, I was thinking of making one my self :)

@dslul Awesome work with openboard please keep it up.

Now regarding the wordlists from the link you provided, it seems like Greek is already [included](https://github.com/dslul/openboard/blob/master/dictionaries/el_wordlist.combined.gz)?? 

Does that mean that Greek is now officially supported? 

I too was expecting a gr pprefix (for Greek) but for some reason el (ellinika) is being used.

Reference here --> https://github.com/hermitdave/FrequencyWords/tree/master/content/2016/el

**Comment by dslul** [comment]
@irowea you're right, I added it in the last commit.

**Comment by irowea** [comment]
Excellent news! Thank you very much, feel free to close the ticket :+1:
