### ISSUE TITLE
Language preferences lost on upgrade

### ISSUE THREAD

**Issue by MisterY** [dslul/openboard#39]
After the update today, I noticed that the language preferences are lost. The same has happened earlier when the device was reset but I didn't pay much attention at the time.
The selected theme is there but not the languages that were previously selected nor are the custom Dvorak layouts for languages shown in the list of languages to use.
The custom layouts can still be found in the Custom Layouts section. This corrects after some time (restart? can't remember).
Posting in case this is not an expected outcomes of the standard update.

**Comment by dslul** [comment]
I cannot reproduce this issue. Tell me if it happens again.
