### ISSUE TITLE
[Feature Request] Automatic space after dot/full stop or comma

### ISSUE THREAD

**Issue by GambaJo** [dslul/openboard#41]
It would be useful if the keyboard will add a space after dot/full stop or comma, except the char before the dot/comma is numeric.

**Comment by dslul** [comment]
I don't know if it's a good idea, it's not easy to understand when you want a space and when you don't (if you write some code for example, or abbreviations such as Sig.ra in some languages). I think it's better to leave this up to the user.

**Comment by TheCrowned** [comment]
Uhm, I'd still reevaluate this. After all, it is much more common to write text rather than code on a phone, and I believe it should be optimized for that,no?

**Comment by kojid0** [comment]
I'd also very much apprentice this.
