### ISSUE TITLE
Reassign comma to emoji/language

### ISSUE THREAD

**Issue by dragonattheend** [dslul/openboard#430]
In my layout of English (US) the bottom keys are 

?123 , spacebar . Enter 

I don't really use comma key on the left:  I'm used to holding dot and getting it from there. And I use the dot by double-tapping spacebar. 

I see that by holding comma key I can get emojis and language switch. 
How can I replace the comma key to either emoji key or language switch permanently?

**Comment by MajeurAndroid** [comment]
You have an option in settings to show language switch key or emoji key permanently, however it will not replace comma key.
