### ISSUE TITLE
Some word suggestions are in all caps

### ISSUE THREAD

**Issue by vincentmathis** [dslul/openboard#438]
**Describe the bug**
Words are sometimes only suggested in all caps. It's quite annoying in daily usage.

**To Reproduce**
1. Use German language
2. Type "plattensp"
3. Suggestion shows **only** "PLATTENSPIELER"

**Screenshots**
![Screenshot_20210922-211239](https://user-images.githubusercontent.com/33002126/134407827-530f5671-2c5d-4284-b7d9-35703407ab94.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - OS: Android 11

**Additional context**
I'm unsure if there is any pattern which words are all caps. Sometimes if I add one character and delete it again, it shows the word in normal capitalization.

**Comment by chaptergy** [comment]
I'm encountering the same thing for a few weeks now. I've noticed it with the word 'handy' but also a few more which I unfortunately do not remember. I've tried to "teach" the correct spelling as well by writing it multiple times and choosing the correct spelling with just the first letter capitalized, but it still keeps correcting it to all caps.
This only seems to be an issue with the German dictionary, as I have not encountered it using the English keyboard. I'm also on Android 11.

**Comment by jnnkB** [comment]
I just looked into the german dictionary and since https://github.com/dslul/openboard/pull/308 it contains these all caps words. Maybe we should revert that change? @sandsturm You created that PR. What do you think? Did this commit contain other changes to the German dictionary?

**Comment by dslul** [comment]
Sorry for this, I approved the revert.
