### ISSUE TITLE
Word suggestion: make border wider

### ISSUE THREAD

**Issue by kojid0** [dslul/openboard#44]
Long word suggestions often get cut although there is still lots of space left. See screenshot. 
It would be nice if the border can be widened in order to use all display space available and/or to reduce the text size of long suggestions by max. 25% (so that you can still read it). 

![IMG_20200130_141754_861](https://user-images.githubusercontent.com/24477557/73452970-57186680-436b-11ea-8cc7-5918852701dd.jpg)

**Comment by kojid0** [comment]
Closing this since there is the incognito icon on the left side now and maybe a clipboard-paste icon on the right soon?

**Comment by dslul** [comment]
> and maybe a clipboard-paste icon on the right soon?

As the code suggests, there will be a "more" button with additional actions :)

**Comment by kojid0** [comment]
I'm excited😅
