### ISSUE TITLE
[BUG] Blank autocorrect in Simplenote app

### ISSUE THREAD

**Issue by ascworl** [dslul/openboard#440]
If you go to Simplenote app and type, the suggested words for autocorrect do not display at all. It is blank.

Also, I hope the autocorrect feature gets a bit better. I notice SwiftKey really is good at auto correcting. Openboard only sometimes corrects the word. Swiftkey corrects is 90% of the time.

Thank you

**Comment by jnnkB** [comment]
Duplicate if #275
