### ISSUE TITLE
There's a bug in your legal interpretation

### ISSUE THREAD

**Issue by TechnikEmpire** [dslul/openboard#442]
**Describe the bug**
Someone didn't consult a lawyer and thought they could take a 100% Apache 2 project and change it to GPL v3.

Aside from the fact that you cannot legally relicense something unilaterally, GPLv3 is only 1-way compatible with Apache 2 when the substantial part of the codebase is already GPLv3 and is bringing in a small dependency that is Apache 2. When 100% of the code-base was already Apache 2, it's explicitly a violation of the GPLv3, as explicitly agreed and publicly documented by both the Apache Foundation and FSF. In other words, if you wanted your additions to be licensed under the GPL and revert the original code back to Apache 2, that would not be legal either. 

To be extra clear, an "addition" here would be an entirely new file that is completely unique and not derived from the original code base. Anything else would be you using and re-publishing under the original license of the modified source file, whether you like it or not.

**To Reproduce**
1. Hire a lawyer.
2. Confirm what I've told you.
3. Update the LICENSE file to appropriately state that this work is Apache 2, not GPL.

**Expected behavior**
That people would at least have some familiarity with copyright law and contract law before they decide to pretend they're a lawyer.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All

**Additional context**
N/A

**Comment by TechnikEmpire** [comment]
Sources:

https://www.apache.org/licenses/GPL-compatibility.html

**Comment by TechnikEmpire** [comment]
Ah ok so you're going to just close my ticket and ignore it. 2 things are going to happen now. 1) I'm forking this and changing the license back to the original license and 2) I'm filling out a DCMA. Good luck.

**Comment by dslul** [comment]
Are you a lawyer? I don't think so. With the current license you cannot fork the entire repo and change the license arbitrarily.

from apache 2.0:
> You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

**Comment by TechnikEmpire** [comment]
Thanks for acknowledging that the original license is Apache 2. You didn't dual license, and you cannot do what you think this empowers you to do.There is no need to argue. I reported it to everyone so when your stuff gets a takedown then we'll know who was right.On Jan. 22, 2022 1:35 p.m., Daniele Laudani ***@***.***> wrote:
Are you a lawyer? I don't think so. With the current license you cannot fork the entire repo and change the license arbitrarily.
from apache 2.0:

You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

**Comment by NoahAndrews** [comment]
He didn't delete the copyright headers in the source code saying that it's licensed under Apache. The original code is still Apache, and attribution for that is present. No one's denying that. It's just the modifications and the final product that are under the GPL. The Apache license explicitly allows this, as previously quoted.

The one thing I'd say is that any files modified in this project should probably contain a second copyright headers referencing the GPL. Otherwise the whole file might be interpreted as being Apache-licensed.

**Comment by TechnikEmpire** [comment]
You cannot legally include gpl software in an apache 2 software. The GNU and the Apache foundations both agree on this. It's called one-way compatibility.It is impossible legally for any contributions to be offered under the GPL and thus you have tens of thousands of users running your copyright that legally has all rights reserved. They have no legal right to it.Your foolishness here pretending you know things you do not has left tens of thousands of people open to liability claims and your repository is in an illegal state violating the original license.On Jan. 22, 2022 3:00 p.m., Noah Andrews ***@***.***> wrote:
He didn't delete the copyright headers in the source code saying that it's licensed under Apache. The original code is still Apache, and attribution for that is present. No one's denying that. It's just the modifications and the final product that are under the GPL. The Apache license explicitly allows this, as previously quoted.
The one thing I'd say is that any files modified in this project should probably contain a second copyright headers referencing the GPL. Otherwise the whole file might be interpreted as being Apache-licensed.

**Comment by TechnikEmpire** [comment]
> Are you a lawyer? I don't think so. With the current license you cannot fork the entire repo and change the license arbitrarily.
> 
> from apache 2.0:
> 
> > You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

From your own reply:

> provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

Statement from the ASF linked above:

> However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.

**Comment by NoahAndrews** [comment]
That statement at the end says that you cannot include GPL software into an Apache project, but OpenBoard did the opposite: it incorporated Apache licensed software (the AOSP keyboard) into a new GPL project. That is exactly the one-way incorporation that is allowed.

**Comment by TechnikEmpire** [comment]
> That statement at the end says that you cannot include GPL software into an Apache project, but OpenBoard did the opposite: it incorporated Apache licensed software (the AOSP keyboard) into a new GPL project. That is exactly the one-directional compatibility that is allowed.

Oh my goodness. The "project" here already exists. It was the AOSP keyboard. By your definition, if I create a new repo and name it "my project" and copy your source into it, its now a "new project". It's not.

I'm gonna unsub from notifications now. Maybe sit and think about how this is the only fork of AOSP that has a different license than the original fork. It is not legal, no matter how much you try to reduce international copyright law down to a kindergartener's understanding of plain language.

**Comment by dslul** [comment]
@TechnikEmpire the webpage you got so fixated on is referring to APACHE software, not any other project!
This derivative work is released under GPL v3, and there is nothing to discuss about this.

taken from: https://www.whitesourcesoftware.com/rc-content/wp/the-complete-guide-for-open-source-licenses-2020.pdf

> You can choose to release the modified or derived products under different licenses, the unmodified parts of
> the software, however, must retain the Apache License, and you cannot name your modified version in any
> way that suggests that the final product is endorsed or created by the ASF.
> ...
> Apache License 2.0 is compatible with GPLv3, so you can freely mix the code that’s released under these two
> licenses. The resulting software, however, must be released under GPLv3.

Just a sidenote: I strongly encourage you to learn how to interact with people without being toxic.

**Comment by TechnikEmpire** [comment]
@dslul I interact very well with people who are not IP thieves. I posted a comment from the ASF, the authority on the license of the IP you're stealing and re-relicensing. Stop tagging me.

**Comment by dslul** [comment]
> @dslul I interact very well with people who are not IP thieves. I posted a comment from the ASF, the authority on the license of the IP you're stealing and re-relicensing. Stop tagging me.

@TechnikEmpire These public false accusations would be a felony in my country, you're lucky you don't live here.
Learn to read (taken from the page you posted): 

> **the GPLv3 license accepts our software into GPLv3 works**

This project is GPLv3, not APACHE. I can include any apache 2.0 licensed code in a GPLv3 software.

> **This licensing incompatibility applies only when some Apache project software becomes a derivative work of some GPLv3 software**

This means that **you cannot take a GPLv3 software and create a derivative work licensed under APACHE 2.0**, and it would also be logical, since the former is a less permissive license. And according to them, this is THE ONLY CASE.

**Now repeat with me: this is NOT a derivative work of some GPLv3 software.**

Is it clear now?
