### ISSUE TITLE
OpenBoard does not show autocorrect pane when typing into SearchBar Ex app

### ISSUE THREAD

**Issue by KeronCyst** [dslul/openboard#45]
I basically live off of [SearchBar Ex](https://play.google.com/store/apps/details?id=com.devhomc.search) and when typing into the search bar via OpenBoard, I get no autocorrect help. 😥

**Comment by dslul** [comment]
I am aware of this issue, I'll try to fix it in the next update.

**Comment by jwsp1** [comment]
Looks like this is related to bug #12

**Comment by kojid0** [comment]
> I am aware of this issue, I'll try to fix it in the next update.

Any ETA? This bug is very annoying... 😅 Let me know if I can help

**Comment by dslul** [comment]
> Any ETA? This bug is very annoying... sweat_smile Let me know if I can help

Fixed in a6d7e2d3ac87b6335d9f118ef750e9c1cca7c97b but still needs testing.
