### ISSUE TITLE
Outated release on github, f-droid and google play

### ISSUE THREAD

**Issue by blennster** [dslul/openboard#454]
**Describe the bug**
The most recent release is too old and therefore Swedish, Danish and Hungarian dictionaries are missing. I'm sure a lot of other features are missing also.

**Additional context**
I have created a pull request (#453) which address compilation problems.

Thanks.

**Comment by blennster** [comment]
Here is a signed release build.

Created at 2021-10-16 22:51:24 CEST
[app-relase.zip](https://github.com/dslul/openboard/files/7358255/app-relase.zip)

**Comment by blogmangit** [comment]
> Here is a signed release build.
> 
> Created at 2021-10-16 22:51:24 CEST
> [app-relase.zip](https://github.com/dslul/openboard/files/7358255/app-relase.zip)
> 
> 
> 

hi there can u do something ie disable long press on spacebar to switch input since we already have a language button for it. and post the apk here please.

**Comment by dslul** [comment]
I pushed the new release to github and play store (f-droid users will need to wait a little while their servers compile it from source)
