### ISSUE TITLE
OpenBoard cannot be opened with MIUI

### ISSUE THREAD

**Issue by ghost** [dslul/openboard#46]
If MIUI users disable this option in the App: Show app icon

There is no way to get back to the OpenBoard settings. When user try to press the comma key for a long time to reach OpenBoard settings this way. It doesn't work.

The cause. It only appears in MIUI and probably other Android systems that do something similar.

Here's the link.
https://stackoverflow.com/questions/56295901/miui-permission-denied-activity-keyguardlocked

There are no direct instructions if MIUI users want to return to the Openboard settings using the method (press comma key). But then wonder why nothing happens.

On MIUI 11 (Android 9) this has to be activated to solve this.

Settings -> Apps -> Manage apps -> OpenBoard -> Other permissions -> enable: Display pop-up windows while running in background

**Comment by licaon-kter** [comment]
Can't repro on MIUI11 Android 10 here, also you can always setup in Settings/System/Language...

**Comment by AlanSanchezP** [comment]
I have this issue too on MIUI 11 (Android 9) and had already mentioned it on #22 , but I never got the change to take stack traces so didnt say anything after they closed the issue. Glad to see you found a workaround.

**Comment by dslul** [comment]
Thanks for the workaround!

**Comment by swiesend** [comment]
This workaround works also for MIUI 12.5.7 on a POCO F3
