### ISSUE TITLE
OpenBoard crashes on opening numeric pad

### ISSUE THREAD

**Issue by Gene-W** [dslul/openboard#463]
**Describe the bug**
Quite similar to [#176 ](https://github.com/dslul/openboard/issues/176)
When a numeric pad opens, keyboard crashes. It doesn't happen when typing numbers otherwise, only when a form or website, etc requires numers in a way that opens the numbers pad.

Usin OpenBoard 1.4.3

**To Reproduce**
1. Go to 'any site or form requiring numeric entry'
2. Click on 'number entry field'

**Expected behavior**
Number pad opens, ability to enter numbers.

**Smartphone (please complete the following information):**
 - Device: Asus Zenpad 10 P027
 - OS: Android 7

**Comment by dslul** [comment]
Fixed in the latest 1.4.4 release.
