### ISSUE TITLE
v 1.6.1 dots issue

### ISSUE THREAD

**Issue by bronskeey** [dslul/openboard#464]
After updating version to 1.6.1 I start to having those dots at the beginning of every line.

Driver reinstalled, OpenBoard reinstalled, tablet replugged.

Windows 10 Pro 20H2
Wacom Bamboo CTL-470K
OpenBoard 1.5.4, 1.6.1

![v 1 5 4](https://user-images.githubusercontent.com/88116571/139486283-9db3436a-ac25-4da2-8c08-f370d7133b99.png)
![v 1 6 1](https://user-images.githubusercontent.com/88116571/139486287-4703cec8-1df9-41db-8e24-3d60a43d02c6.png)

**Comment by jnnkB** [comment]
Hey, I think you might be looking for this repository: https://github.com/OpenBoard-org/OpenBoard. This openboard is a keyboard :)
