### ISSUE TITLE
Word suggestions in two languages.

### ISSUE THREAD

**Issue by davidj77** [dslul/openboard#471]
Hi, I think it would be great if we can receive word suggestions in two languages at the same time.
For example, I'm writing in Spanish but I need to write a word in English and I don't want t to change keyboard language settings to English only for write a word.
Google keyboard has this feature and it will be useful I you add this on OpenBoard.
Thanks in advance.

**Comment by jnnkB** [comment]
Duplicate of either #7 or #167
