### ISSUE TITLE
Can't show numbers.

### ISSUE THREAD

**Issue by Pranab009** [dslul/openboard#472]
**Describe the bug**
It can't show numbers which are saved in personal dictionary.

**To Reproduce**
1. Go to 'personal dictionary then add any number like 
 67676767 
Shortcut 676 ' saved it
2. Open keyboard 'type 676 (shortcut)'
3. Suggestion bar is empty.
**Expected behavior**

**Screenshots**

![Screenshot_20211208-154610](https://user-images.githubusercontent.com/65340361/145190989-c04cd337-f279-4585-ac89-e0cadee622bf.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. micromax in 1]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by GithubContributor832** [comment]
That shouldn't be a bug. The dictionary is for words not numbers. The default AOSP keyboard don't do it either:)

**Comment by Pranab009** [comment]
Okk..thanks for your reply....
