### ISSUE TITLE
Keyboard fails to open in numeric layout, when joining a "Zoom Meeting"

### ISSUE THREAD

**Issue by atom-smasher** [dslul/openboard#479]
**Describe the bug**
Keyboard fails to open in numeric layout, when joining a "Zoom Meeting"

**To Reproduce**
Steps to reproduce the behaviour:
1- Open "Zoom Meeting" app
2- Tap "Join a Meeting"
3- Tap "Meeting ID"; OpenBoard opens in default layout
4- Tap "?123" on the keyboard, to open the numeric layout
5- Fail: The keyboard is gone

**Expected behaviour**
Expected behaviour A: After tapping on "?123", the numeric layout should appear. The keyboard should not disappear.

Expected behaviour B: After tapping "Meeting ID", the keyboard should open directly into a numeric layout.

Workaround 1: Tap the back-button; click "Join a Meeting", and the keyboard opens. This allows the inconvenient typing of numbers using the top row "QWERTY" keys.

Workaround 2: Disable OpenBoard, and select a different keyboard.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy SM-T580, aka T580
 - OS: Bliss 12.12
 - Android 10

**Additional context**
Using Gboard, this process opens the keyboard directly to a numeric layout that's different than the "normal" numeric layout.

I'm guessing that the Zoom app is trying to open the keyboard with some kind of configuration/layout that's not supported by OpenBoard, and OpenBoard is not handling this gracefully.

Zoom Meeting -
https://play.google.com/store/apps/details?id=us.zoom.videomeetings
https://zoom-us-zoom.en.aptoide.com/app

**Comment by azukaar** [comment]
In my experience its not just Zoom, any numerical keyboard input will crash the app

**Comment by dslul** [comment]
Fixed in the latest 1.4.4 release.
