### ISSUE TITLE
Language switch key switches to GBoard if it is enabled

### ISSUE THREAD

**Issue by zingmars** [dslul/openboard#48]
I was testing the keyboard, and noticed that if GBoard is present and enabled while using openboard, if you press the "switch language", it will switch to GBoard. 

Here's a video - https://linx.li/s/z022oe34.mp4

OnePlus 6T, Android 10 (OxygenOS 10.3.0), Version 1.3 from Play Store.

**Comment by Glitchy-Tozier** [comment]
It also switches to AnySoftKeyboard.

**Comment by Pentaphon** [comment]
You can disable the language switch key but yes this wouldn't work for people who use multiple languages.

**Comment by natewind** [comment]
Same here.

**Comment by dslul** [comment]
Fixed.
