### ISSUE TITLE
Clipboard history entries get double-added

### ISSUE THREAD

**Issue by NoahAndrews** [dslul/openboard#487]
See this video: https://user-images.githubusercontent.com/10224994/149680631-91890a1a-e7f2-4a38-aa70-705a348a816b.mp4

**Smartphone:**
 - Device: Pixel 6
 - OS: Android 12

**Comment by dslul** [comment]
Does this always happen? I can't replicate this bug on my device

**Comment by MajeurAndroid** [comment]
This bug is weird. I never encountered it during development. Anyway, I planned to add a check to avoid having doublons, that will fix this. 
Still, I'll have a look to the code to investigate.

**Comment by NoahAndrews** [comment]
Yes, this happens every time. I also just rebooted my phone for a security update, and that did not help.

**Comment by MajeurAndroid** [comment]
Can you try to reproduce the bug with [this apk](https://drive.google.com/file/d/1VnLsvLl19t6fIpuQ8ieFiGVVht54ExZu/view?usp=sharing) ?

**Comment by NoahAndrews** [comment]
I uninstalled OpenBoard, installed the debug APK, and got this error.
![Screenshot_20220118-181631.png](https://user-images.githubusercontent.com/10224994/150039687-b1e8e4d3-b7f0-4771-9310-ff06efbb02bb.png)

**Comment by MajeurAndroid** [comment]
Sorry for that, [this one](https://drive.google.com/file/d/1nzxihPD1wTXYQaW68KV6kMcK3H6gSFpu/view?usp=sharing) should be ok.

**Comment by NoahAndrews** [comment]
Nice, I can't reproduce the issue with that APK.
