### ISSUE TITLE
Import enhancedime features like number row

### ISSUE THREAD

**Issue by r3muxd** [dslul/openboard#49]
https://github.com/Hardslog/platform_packages_inputmethods_EnhancedIME

**Comment by r3muxd** [comment]
i'll make a PR for this later

**Comment by adrium** [comment]
+1 for the number row!

It is also available in https://github.com/rkkr/simple-keyboard

**Comment by trymeouteh** [comment]
This is all I need! Please add optional number row.

**Comment by kojid0** [comment]
@r3muxd what's the state of development of your PR?

**Comment by dslul** [comment]
See #21
