### ISSUE TITLE
Clipboard for openboard [Enhancement] 

### ISSUE THREAD

**Issue by L1VEWIR3** [dslul/openboard#493]
**Problem:**
Whenever copying text from one app to another i have to manually hold down the cursor in the search bar to paste the text.

**Solution:**
It would be nice to add an special button for the clipboard and whenever copying text and shifting to the next app, it should be able to pop up in the suggestions, allowing the user to simply click it to enter the text.

**Alternative**
Ive run into a couple of apps which offer copy and pasting of text, but problem is these apps need to run in the background causing battery drainage.

**Additional context**
Google's Gboard has this option, it would be nice to see it implemented in openboard!

Thank you for your work!

**Comment by MajeurAndroid** [comment]
See 1.4.4 release.
