### ISSUE TITLE
Clipboard content hard to read with dark theme

### ISSUE THREAD

**Issue by mariomie** [dslul/openboard#496]
**Describe the bug**
The content of the clipboard is hard to read if dark keyboard theme (material dark) is selected. With light theme everything is fine

**Expected behavior**
White font for dark theme

**Additional context**
Thanks for adding the clipboard feature 👍

**Comment by MajeurAndroid** [comment]
Can you attach a screenshot illustrating your issue ? Which android version are you running ?

**Comment by mariomie** [comment]
Hmm, now when I wanted to make the Screenshot every thing is working as intended. Was maybe just a temporary problem after the update. Sorry, I will close the issue. And again thanks for the new feature.
