### ISSUE TITLE
Force Closed when opening preferences, appearance & layout, text correction and advance

### ISSUE THREAD

**Issue by zputnyq** [dslul/openboard#499]
Open board version : 1.4.4
Device info
Device Name: Xperia M4 E2306
Android version: 6.0.1

Hi, it's my first time using this keyboard & it's really good. However I get an issue when opening those sections stated in title, it' force closed.
I have a logcat for it.
[logcat.txt](https://github.com/dslul/openboard/files/7918669/logcat.txt)

**Comment by dslul** [comment]
Thanks for reporting this, it's a compatibility issue with older android version. I'll try to fix it as soon as possible.

**Comment by dslul** [comment]
I pushed a new release with the fix. If you use the f-droid version, you need to wait for them to compile the new source code._

**Comment by zputnyq** [comment]
Thank you, I really appreciate it.
This new release fix this issue.
