### ISSUE TITLE
Contacts permission should be removed entirely?

### ISSUE THREAD

**Issue by Pentaphon** [dslul/openboard#50]
The contacts permission is the only one left in 1.3. Do any of my fellow users think it should be removed entirely? I think so, but I'm wondering what other people think.

**Comment by jwsp1** [comment]
I don't see much use/improvement by this feature. It's just about names of my contacts? I belive names are part of the languages/dictionaries, or am I wrong?

**Comment by dslul** [comment]
It should suggest emails, but I noticed it's not working as it should.

**Comment by Pentaphon** [comment]
@dslul I think if Simple Keyboard doesn't have the contacts permission, then neither should Openboard. Especially if you want to convince users this keyboard is serious about privacy.

**Comment by dslul** [comment]
> @dslul I think if Simple Keyboard doesn't have the contacts permission, then neither should Openboard. Especially if you want to convince users this keyboard is serious about privacy.

I didn't remove it because I want to fix the prediction to show suggestions from contacts (emails, names etc). If you don't want it, you can deny permission, and it is opt-in by default. Simple Keyboard doesn't need it because it doesn't have prediction.

**Comment by Pentaphon** [comment]
> I didn't remove it because I want to fix the prediction to show suggestions from contacts (emails, names etc). If you don't want it, you can deny permission, and it is opt-in by default. Simple Keyboard doesn't need it because it doesn't have prediction.

Fair enough.

**Comment by Pentaphon** [comment]
Thanks for removing the permission in 1.4.2
