### ISSUE TITLE
reduction of emojis

### ISSUE THREAD

**Issue by Bondarz** [dslul/openboard#51]
Hello,

can the number of emojis be reduced?
example people with skin colours, here you have to scroll for a long time. is a simple tap on the figure enough to choose the colour?

thanks :)

**Comment by ChildishGiant** [comment]
Duplicate of #6

**Comment by dslul** [comment]
I was planning to replace/overhaul the emoji keyboard entirely, with something that resembles the telegram one. We can keep the discussion on the other thread. I'll close this one.
