### ISSUE TITLE
When swipe backspacing, automatic capitals are not renewed

### ISSUE THREAD

**Issue by ChildishGiant** [dslul/openboard#56]
I don't know quite how to word it but here's a video of what I mean. 
[decentacidicamberpenshell](https://gfycat.com/decentacidicamberpenshell)
![DecentAcidicAmberpenshell](https://thumbs.gfycat.com/DecentAcidicAmberpenshell-size_restricted.gif)

**Comment by TheCrowned** [comment]
@dslul do you have any hints on this? I'd love to contribute and fix this, but find it a bit hard to understand where to start ^^

**Comment by dslul** [comment]
> @dslul do you have any hints on this? I'd love to contribute and fix this, but find it a bit hard to understand where to start ^^

Most of the logic starts from LatinIME.java. In this case, onUpWithDeletePointerActive needs to be fixed.

**Comment by dslul** [comment]
@TheCrowned thanks!
