### ISSUE TITLE
[Request a feature] Switch languages ​​with space bar

### ISSUE THREAD

**Issue by afmbsr** [dslul/openboard#57]
Is there a possibility to include the option to switch languages ​​by dragging with the spacebar, due to the difficulty of rapid adaptation, especially for those who are used to using swiftkey and samsung keyboards, which forces them to return to the mentioned panels .. Thank's

**Comment by MisterY** [comment]
What exactly do you mean?
If you long-press the spacebar, the list of languages will appear and you can switch a language. This technically satisfies the request from the title.
Sliding sideways on the spacebar moves the cursor, so that gesture is already taken.
Could you add some clarification as to what is supposed to happen and how?

**Comment by hugoncosta** [comment]
@MisterY, the way SwiftKey has implemented switching keyboards/languages is by swiping the space bar. It's faster than long pressing and then selecting from a list, especially since the majority of users only write in two keyboard types (Latin and Cyrillic for example)

**Comment by MisterY** [comment]
@hugoncosta, sounds familiar. Google's keyboard may have had it that way at some point. Having a setting for switching the behaviour would be convenient.
I normally use three languages and it is inconvenient switching them all the time, especially as today we use so many English words, so the languages get mixed within one sentence.
I find the way Gboard does it very convenient. It uses all the selected dictionaries and somehow tries to guess the context.

**Comment by jwsp1** [comment]
> @hugoncosta, sounds familiar. Google's keyboard may have had it that way at some point. Having a setting for switching the behaviour would be convenient.
> I normally use three languages and it is inconvenient switching them all the time, especially as today we use so many English words, so the languages get mixed within one sentence.
> I find the way Gboard does it very convenient. It uses all the selected dictionaries and somehow tries to guess the context.

Multi-language-support is being discussed in #7. This would be awesome and solve many related issues here.

**Comment by OpenWarp** [comment]
Coming from TouchPal that is using space bar to switch languages which is indeed very convenient, I have no regret for trading that off to the ability to move a cursor with space bar. To me, this is the best implementation of controlling the cursor as I am having hard time to use e.g. volume buttons to do the same thing. While mastering to switch languages was a less sacrifice as long as I disabled all other keyboards. Not to mention that in most situations pressing the "Globe" button will do.

**Comment by peter11star** [comment]
Hello.


So I love your keyboard. But the one thing its missing is the ability to add an emoji button somewhere. If its possible, can you please add this feature?


Thanks,


-Peter

**Comment by ChildishGiant** [comment]
> But the one thing its missing is the ability to add an emoji button somewhere. If its possible, can you please add this feature?

If you hold down on enter, you get an emoji option

**Comment by peter11star** [comment]
No no no. I know about that. I'm talking about a button that can be put somewhere on the keyboard. 
![Screenshot_20200329-234608_Chrome](https://user-images.githubusercontent.com/48706671/77873281-81758b80-7217-11ea-8afc-d158e804d865.jpg)

**Comment by ChildishGiant** [comment]
Ah yea, that'd be nice

**Comment by dslul** [comment]
I don't think I'll implement this. The goal is #7
