### ISSUE TITLE
Space bar trackpad not working in web browser text fields

### ISSUE THREAD

**Issue by lriesebos** [dslul/openboard#58]
The space bar trackpad feature is working as expected for most fields, but for some reason it does not work well with fields in the (Firefox) web browser. The cursor does not move or it looks like it wants to move but jumps back to its original position.

Tested with Firefox and Firefox preview which show the incorrect behavior in text fields on all websites I tried so far, including the search fields of google.com and duckduckgo.com. Other keyboards with a similar space bar trackpad feature, such as "simple keyboard", do not suffer from this issue.

Android 10, OpenBoard v1.3.

**Comment by TheCrowned** [comment]
I would add Facebook messenger from the browser in desktop version as a test case, it happens there as well!

**Comment by dslul** [comment]
@TheCrowned did you try if it happens with master?

**Comment by TheCrowned** [comment]
@dsul yes, just tried. I also think I have nailed it down to an easy-to-reproduce scenario.
I tested it on the username login field of Github with Fennec, but I guess any form would work equally well.
Write whatever you want. Try to do a group delete by holding backspace and swiping left. It should only delete the last char. It also looks like the appearance of the delete button changes. If you repeat the backspace-swipe-delete, it will delete chars in the middle of the text.

**Comment by dslul** [comment]
> @dsul yes, just tried. I also think I have nailed it down to an easy-to-reproduce scenario.
> I tested it on the username login field of Github with Fennec, but I guess any form would work equally well.
> Write whatever you want. Try to do a group delete by holding backspace and swiping left. It should only delete the last char. It also looks like the appearance of the delete button changes. If you repeat the backspace-swipe-delete, it will delete chars in the middle of the text.

Do you mind trying with the latest patch? The problem here is that many apps don't behave correctly, both when setting selections with software or by emulating hardware keys. GBoard sometimes has the same problem, but not as often.

**Comment by TheCrowned** [comment]
I definitely looks much, much better! Can't say it's fixed everywhere, but on a couple cases I tried, it is fine now! Great!

**Comment by Glitchy-Tozier** [comment]
It does look WAY better, but it's still not completely gone.
The most common thing I still get is that when I have a 15-20-letter text and i swipe from the end to the beginning of the text the cursor will stop _one letter_ before it hits the beginning-spot. Example:
This:
M|y sentence :)
instead of
|My sentence :)


 it will take 2-3 tries to get the cursor to the actual beginning of the sentence. Therefore, while the worst behaviours were corrected, I suggest reopening this bug.
