### ISSUE TITLE
Consolidate emoji skin tones

### ISSUE THREAD

**Issue by yaomtc** [dslul/openboard#6]
The emoji list in this keyboard has the same issue as the AOSP keyboard: every emoji that has multiple skin tones available shows each skin tone as a separate item in the list. This makes the emoji list extremely cluttered and difficult to navigate. Other keyboards allow a long-press on the default yellow emoji to choose a skin tone. That might be the best approach. Or you could choose a default skin tone in the settings and only display that skin tone in the list.

**Comment by hockeymikey** [comment]
I kinda like the approach having the ability to chose a default skin tone and then having the long pressed options off of it from there.

**Comment by yaomtc** [comment]
For users of LineageOS, this issue has now been "solved" in their Android Keyboard as of 17.1... They got rid of all the different skin tones in favor of just yellow.

**Comment by yaomtc** [comment]
Worth mentioning that [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard) has this feature, if someone wants to look at how they implemented it.

**Comment by marcdw1289** [comment]
Confused. Has this issue fixed (upcoming)? Whatever "fix" is in LOS 17.1 has no relevance elsewhere. Nougat, Oreo, Pie, and OxygenOS 11, the endless scrolling through skin tones has yet to change.
Keep coming back to this keyboard hoping the behavior has changed.

**Comment by yaomtc** [comment]
Relax, @marcdw1289. It's coming in a future release of OpenBoard, as you can see by the code merge linked just above your comment. If you want it right this minute, you can use `git` and compile the latest version of the code into an APK, if you can get it to compile and don't mind being an alpha tester.

There is a pre-compiled APK of a beta version available here that does reduce the number of emoji. It doesn't have the long-press for different skin tones yet, though, for me at least.

**Comment by dslul** [comment]
> There is a pre-compiled APK of a beta version available here that does reduce the number of emoji. It doesn't have the long-press for different skin tones yet, though, for me at least.

Did you use the latest beta apk? It's strange it doesn't work. What Android version?

**Comment by marcdw1289** [comment]
Hee hee. I was riled up yesterday for other reasons. "Problematic Software Day". Apologies all around. 😥

**Comment by yaomtc** [comment]
@dslul this is on a Pixel 4a with GrapheneOS (Android 11)

**Comment by yaomtc** [comment]
@dslul 
Oh. I just noticed it actually DOES work, I just didn't realize the face emojis don't have skin tone options - only the people and the hand emojis. My mistake!

**Comment by bennypr0fane** [comment]
So it's been fixed for a while now - do we have a timeline for the release that'll include this fix?

**Comment by ChildishGiant** [comment]
This change isn't available on f-droid still
