### ISSUE TITLE
Clipboard (cut/copy/paste) functionality

### ISSUE THREAD

**Issue by MisterY** [dslul/openboard#60]
Some keyboards offer the clipboard manipulation with cut/copy/pasting of the text. This is very useful in certain situation, like when working on in a terminal, where the system long-press is not possible.
Having an explicit option (menu/button/whatever) is much more preferable.

**Comment by ChildishGiant** [comment]
Duplicate of #16

**Comment by MisterY** [comment]
@ChildishGiant, I disagree. These are close but not the same as far as I can see. That request is very specific, with repro steps.
This is a generic cut/copy/paste functionality with dedicated buttons. At least that's how I see it.

**Comment by dslul** [comment]
Related #84.
