### ISSUE TITLE
Add emoji button when ENTER is shown

### ISSUE THREAD

**Issue by licaon-kter** [dslul/openboard#61]
...eg. on the left side of SPACE

**Comment by jwsp1** [comment]
Space bar is indeed pretty big/wide, so there could be an Emoji key on the left side of it 👍🏼

**Comment by GLLM** [comment]
Please, make it optional, as i really like having a suite wide [Space] key !

**Comment by dslul** [comment]
Sure, I'll add an option like on gboard in the next update (I'm quite busy these couple of weeks, so expect it to come next month unless someone sends a PR).

**Comment by OpenWarp** [comment]
And vise versa. In Conversations, there is emoji button in place of "Enter" key. And I cannot find a way to revert the keyboard to normal layout. When an option to display emoji key is implemented there is no reason to sacrifice the so much needed "Enter" key any more. Under no circumstances shall emoji button replace the "Enter" button, period.

**Comment by sdwolfz** [comment]
@OpenWarp After digging through code, I found a comment at `app/src/main/res/xml/key_styles_enter.xml:248` saying you hold SHIFT then the enter button is displayed instead of the emoji button. Tried it and it works :exploding_head:.

**Comment by kojid0** [comment]
Or simply show an Emoji key hint (long press) on the Enter key itself?

**Comment by Fzndox** [comment]
I'd like an option to hide the emoji key altogether. When replying to texts and stuff all I have is a big emoji button on the bottom right. I'm used to that being a "send" button. I also like the big space bar! Leave it please!

**Comment by Fzndox** [comment]
> And vise versa. In Conversations, there is emoji button in place of "Enter" key. And I cannot find a way to revert the keyboard to normal layout. When an option to display emoji key is implemented there is no reason to sacrifice the so much needed "Enter" key any more. Under no circumstances shall emoji button replace the "Enter" button, period.

110% this^ it happens for signal too. It's the only thing stopping me from making this keyboard atm. I wouldn't mind scrapping emojis altogether on my end, especially if it fixes this.

**Comment by dslul** [comment]
> 110% this^ it happens for signal too. It's the only thing stopping me from making this keyboard atm. I wouldn't mind scrapping emojis altogether on my end, especially if it fixes this.

This is not actually a bug, but it is set by the application (as you can see [here](https://github.com/signalapp/Signal-Android/blob/810365d3340163741ce3f6b4034789969a553a4f/app/src/main/java/org/thoughtcrime/securesms/components/ComposeText.java#L230) from the Signal code). GBoard simply ignores this flag. You can check from [this issue](https://github.com/signalapp/Signal-Android/issues/8019) how to enable the enter key in Signal.

**Comment by Fzndox** [comment]
> > 110% this^ it happens for signal too. It's the only thing stopping me from making this keyboard atm. I wouldn't mind scrapping emojis altogether on my end, especially if it fixes this.
> 
> I removed this functionality in the latest commit, since nobody seems to like it.

Great news, I also disabled system emoji in signal and my return key came back too

**Comment by dslul** [comment]
A bit late, but done now d5339b7ffbfcca222b339a5d0788b2b48d3832fc.

![image](https://user-images.githubusercontent.com/6121202/94697364-69063b00-0338-11eb-9b8c-2b2f11ae5438.png)

**Comment by licaon-kter** [comment]
Thanks
