### ISSUE TITLE
Switch to other keyboards/IME

### ISSUE THREAD

**Issue by zoenglinghou** [dslul/openboard#62]
I am using two keyboards right now: openboard and trime. In trime I can set up the 🌐 icon to switch to a open board keyboard, but not from openboard to trime. I hope openboard can have the same ability so I don't have to long press the globe to select an IME from the menu.

Much appreciated

![my keyboards](https://user-images.githubusercontent.com/11689106/74147461-919fc000-4c03-11ea-994a-aaff1ce5f545.jpg)

**Comment by Glitchy-Tozier** [comment]
1. You could just long press the space-key.

2. If this is implemented, I suggest only making it an optional feature.

**Comment by zoenglinghou** [comment]
>     1. You could just long press the space-key.
That would also bring up the IME menu for selection, which is the same as the language key and keyboard key.

>     2. If this is implemented, I suggest only making it an optional feature.
Agreed.

**Comment by Glitchy-Tozier** [comment]
> That would also bring up the IME menu for selection, which is the same as the language key and keyboard key
What do you mean by "IME menu"?
Also, are you saying this is not the way it should behave?

**Comment by zoenglinghou** [comment]
The "Change Keyboard" Menu as shown in the previous pic.

The thing is, I can switch from trime to openboard with one click, but not from openboard to trime--I have to use the keyboard/IME menu which is slightly inconvenient.

Yeah I know I am sort of nitpicking, but it never hurt to ask if it can be implemented.

**Comment by dslul** [comment]
This is actually intentional, because that button is for switching languages rather than keyboards. But I can make this optional.

**Comment by Glitchy-Tozier** [comment]
@zoenglinghou I completely understand that a 1-button-keyboard-changer is a very nice thing to have. And I agree that this would be a convenient option. 
Not the default, but something that can be turned on in the settings.
(Btw, what is Trime?)

@dslul In that case, there might be a different bug: The language-switch-key also switches to AnySoftKeyboard (https://github.com/AnySoftKeyboard/AnySoftKeyboard) as if it was it's own language.

**Comment by zoenglinghou** [comment]
@Glitchy-Tozier trime is a FOSS Chinese Keyboard. Chinese IMEs can get really specialized lol.

**Comment by zoenglinghou** [comment]
An implementation could be like so:
E.g. I have 2 openboard IMEs. When I press 🌐 for the first time, I might be trying to switch to another openboard. When I press it twice, it is almost certain that I want to use neither of them, then openboard will switch to a different keyboard. I.e. when there are n-openboards, the n-th press of 🌐 switches to another IME.

**Comment by Glitchy-Tozier** [comment]
Another way it could be implemented would be this:
Slow tapping on 🌐 (the Globe-Key) would switch between languages. A fast double-tap would switch to a predefined keyboard of your choosing.

This would basically work the same way as the Shift- / Caps-Lock-Key already works and would not limit the user to a certain number of language switches.

**Comment by tarbib** [comment]
@zoenglinghou Hello! I use keyboard switcher with a pending notification for the need you described : https://gitlab.com/kunzisoft/Android-KeyboardSwitcher
May I ask if trime provide a pinyin input? The app does not start on my phone, this is what I'd like to figure out.

**Comment by zoenglinghou** [comment]
@tarbib yeah Trime requires a lot of configurations to work. It provides all sorts of Chiense inputs.
Better refer to their wiki and Rime's. I configure Rime on my laptop first using [plum](https://github.com/rime/plum/blob/master/README.md) and `adb push` config files into Trime's build folder.

**Comment by dslul** [comment]
I think it's best to keep the globe button for changing between languages for now.
