### ISSUE TITLE
Emoji-Interaction is Buggy

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dslul/openboard#64]
Sometimes, at least in Whatsapp and Telegram, emojis aren't handled properly.

### Possible Errors:
1. Deleting emojis either produces a question-mark (unknown symbol to Whatsapp?) or just doesn't delete it at all.
2. Swipe-deleting sometimes doesn't work.
3. Swiping on the space-bar to go to the other side of an emoji sometimes simply doesn't work. Sometimes it does. Sometimes you need to swipe really far. [Somehow, I feel like this only occurs when trying to move the cursor to the left.]

Emojis that can have different skin-colors seem especially weird, might be just me not testing enough though.

**Comment by dslul** [comment]
For skin color there is already an open issue #6. The rest should be solved, wait for the 1.4 update. If it doesn't, tell me and I'll reopen this issue.
