### ISSUE TITLE
Issue when using whatsapp built in emoji/gif keyboard

### ISSUE THREAD

**Issue by aswfanguy** [dslul/openboard#66]
Ill try to describe the issue the best i can.
 
Sometimes when using whatsapp or telegram and i have the keyboard already opened and press the emoji icon on the input field , the keyboard switches to the whatsapp emoji without issue but then if i try to switch back to the letter pad , the emoji keyoard stays there but clicking it appears letter. almost as if there is a layer on top of the keyboard hiding the letters. This also happens if i try to open up emoji search or gif. It doesnt happen too often but it requires me to completly close whatsapp and reopen it to make it go back to normal. otherwise just exiting the chat and reopening it when the keyboard pops up it will have that extra layer of the emoji keyboard hiding the real keyboard.

**Comment by m-sameer** [comment]
Give screenshots so we could understand better 🙂

**Comment by dslul** [comment]
I'm not sure it's an openboard problem, I couldn't replicate this issue on Telegram, and I use the keyboard on a daily basis.
