### ISSUE TITLE
How to add dictionary?

### ISSUE THREAD

**Issue by Niklas81** [dslul/openboard#68]
I did manage to generate a `.dict` file using the tool in the instruction. But i cannot find any folder that has a `res/raw` subfolder, or any folder for OpenBoard for that matter. Could you please provide further instructions and perhaps a full path?

**Comment by Emiluren** [comment]
I haven't tried it but I assume you need to but it in the source code (this folder [app/src/main/res/raw](https://github.com/dslul/openboard/tree/master/app/src/main/res/raw)) and compile the app yourself.

**Comment by Niklas81** [comment]
When writing my original question, I assumed you could just install the app as usual and then add dictionaries later on. Since then, I've realized you have to build an `.apk`-file and add the dictionaries into it. I learned this by searching for `AndroidManifest.xml`. I've never worked with android apps before, so this is all very new to me. I'm closing this issue and opening another as I'm having trouble building a working `.apk`-file after cloning this and adding a dictionary.
