### ISSUE TITLE
[Feature request] AMOLED theme

### ISSUE THREAD

**Issue by Godecki** [dslul/openboard#69]
AMOLED theme would save soma battery, and it it would also serve another purpose for some people - on Android 10 there is a persistant black bar underneath the keyboard. If the keyboard was perfectly black, the bar would blend into it and it would look much nicer.

**Comment by szaimen** [comment]
Maxbe an option to customize the color would be great like it is implemented in the simple keyboard app. Then you would be able to set it to true black, as well.

**Comment by dslul** [comment]
Done 5e2dbda4e0269ffb929d62dd15a928cf6dbae2da, I changed the material dark to be black instead of, as someone said, racoon s**t.
