### ISSUE TITLE
Please update the Google Play version of the app to the latest version

### ISSUE THREAD

**Issue by MysteriousOrb2000** [dslul/openboard#696]
I noticed that 1.4.5 has been out for almost a month, but the Google Play version is still on 1.4.4. Could you update it?

**Comment by holequantum** [comment]
https://github.com/openboard-team/openboard/issues/619#issuecomment-1208060937
This is your ans

**Comment by Anonymous2716** [comment]
1.4.4b

**Comment by Mrnofish** [comment]
> Could you update it?

See #619 #654 - apparently @dslul is AWOL and the only person who can update the app on Google Play, meaning you can only get updates from Github or F-Droid for the time being.

@MajeurAndroid perhaps this information should be pinned somewhere, if you have the privileges to do that? This issue can be closed.

**Comment by dslul** [comment]
> See #619 #654 - apparently @dslul is AWOL and the only person who can update the app on Google Play, meaning you can only get updates from Github or F-Droid for the time being.
> 
> @MajeurAndroid perhaps this information should be pinned somewhere, if you have the privileges to do that? This issue can be closed.

Thanks for the reminder, I fixed the issues with the play store release, it should be up as soon as google approves it.

**Comment by Mrnofish** [comment]
@MysteriousOrb2000 I apologize if my post sounded a bit like I was telling you to shut up, that was not my intention, I just had other things to do and the post came out a little too curt for its own good.

With that said, there is no need to be rude, especially right after @dslul broke a long silence to promise an update.
