### ISSUE TITLE
(FEATURE REQUEST) GIF FUNCTION

### ISSUE THREAD

**Issue by murph2495** [dslul/openboard#70]
Hi. It would be great if the GIF function could be added to the keyboard. Thank you. regards.

**Comment by kojid0** [comment]
Probably won't come since this needs internet access. Personally, internet access is a big no for me due to security/privacy reasons.

**Comment by dslul** [comment]
The majority of people who use this keyboard doesn't want it to access the internet, so I cannot implement this.

**Comment by rcbyron** [comment]
Looks to me like 9 upvotes vs 2 downvotes at the moment (although to be fair, it's mostly people who want gifs who search for this issue). But please reconsider this one. Internet access does not inherently mean lack of security/privacy. Signal managed to add gif support with Giphy. Plus the feature could be disabled by default for those who do not want it. Or it could be served as a completely separate app (OpenBoard + GIFs). I know a lot of privacy/open-source advocates who DO like to use gifs.

**Comment by patcon** [comment]
Just to note that with the last few weeks of news around AI model for generating art (Dalle-E, Stable Diffusion, Midjourney), I came here wondering whether this might be a keyboard that already had GIF search ability.

I'm wondering which keyboard might be the first to have AI image generation baked into it. Really curious how these models might effect modes of communication once it's right in-flow.

(Some people do self-host the services that do the compute, though I agree that most of how ppl use these tools are not privacy-centered)

Would having two builds (internet + ninternet) be out of the question?
