### ISSUE TITLE
Quick text editing tool

### ISSUE THREAD

**Issue by GoRaN9O** [dslul/openboard#744]
Hi @MajeurAndroid  and thanks for this amazing keyboard it's very good for typing and supports many good features but I doesn't have an editor to quickly edit  text or other content the most wanted tools to help user and make it faster typing is copy & paste select all & cut actions specially when you write an paragraph or long-term texts the text editor panel is very good to have like Gboard or something like this open-source keyboard [FlorisBoard](https://github.com/florisboard/florisboard) it have editing tools on the smartbar and user can customise it like add or remove what tool wants to show at the top bar of main keyboard can you please add Quick Text Editor tools for OpenBoard. Regards 

This is the screenshot of FlorisBoard with smartbar tools enabled.

![Screenshot_20221222_205026_FlorisBoard Beta](https://user-images.githubusercontent.com/3160786/209200430-e9dbbf00-3dcd-43c9-9666-7f15246fdce3.png)

**Comment by jnnkB** [comment]
Duplicate https://github.com/openboard-team/openboard/issues/382
