### ISSUE TITLE
Fix for #660

### ISSUE THREAD

**Issue by RHJihan** [dslul/openboard#745]
**Description**
An option in  Preference to toggle `Force show suggestions everywhere` that will override  [`mShouldShowSuggestions = !(mIsPasswordField || flagNoSuggestions); `](https://github.com/openboard-team/openboard/blob/e9393dfab01dcdfb0872f360b1afe8092777f5ec/app/src/main/java/org/dslul/openboard/inputmethod/latin/InputAttributes.java#L108) to `mShouldShowSuggestions = !mIsPasswordField;`

This will fix #660 as a workaround.
@Helium314, Would you please look at it?

**Comment by odmfl** [comment]
resolved in PR #750 no need to add any other options or weird stuff, this follows the normal behavior of the aosp keyboard
