### ISSUE TITLE
Any way to enable the keyboard ar startup?

### ISSUE THREAD

**Issue by justaguydoinghisstuff** [dslul/openboard#75]
As title says. After reboot if i dont have any other keyboard then i cant type my password.
Is there any way to enable keyboard at launch.

**Comment by Pentaphon** [comment]
> As title says. After reboot if i dont have any other keyboard then i cant type my password.
> Is there any way to enable keyboard at launch.

Isn't it always enabled at launch? It works for me.

**Comment by justaguydoinghisstuff** [comment]
No I get this notification and then it actually does it. it happened to me that after i rebooted it wouldnt appear so i needed to get a hardware keyboard to unlock my phone.
And what bugs me is that obly FOSS keyboards have that simplekeyboard,anysoft, hackers keyboard all share the same issue. But swiftkey and gboard dont.
![Screenshot_20200304-203255](https://user-images.githubusercontent.com/61499129/75916063-e8419800-5e57-11ea-9bdf-7c4f5ef7792c.jpg)

**Comment by SebiderSushi** [comment]
Can you post some more information? It could be helpful to know the following in this case:
- Your device
- Your android version
- Your android variant (preinstalled, custom ROM, ...)
- Whether GBoard and SwiftKey are preinstalled applications
- What kind of encryption you use, i.e.:
&nbsp;- When setting your screen lock, did you opt in to "secure startup"?
&nbsp;- If so, does the problem persist if you disable "secure startup"?
&nbsp;- Do you need to unlock your device during boot or only after the boot process is completed? If you don't know what this means: While turning on the phone, can you see your wallpaper when entering your unlock password for the first time?

**Comment by justaguydoinghisstuff** [comment]
- oneplus 6t
-OxygenOS 10.3.2
- problem was on stock rom now i have rooted and i have never 
- Gboard is preinstalled but swiftkey is not, and that what bugged me as why would swiftkey be different if it too is not a default app.
- i dont have a option for secure boot

> - Do you need to unlock your device during boot or only after the boot process is completed? If you don't know what this means: While turning on the phone, can you see your wallpaper when entering your unlock password for the first time?
i can see my wallpaper but the keyboard wont pop up so i cant unlock my phone. i need to physically insert a keyboard with USB to unlock my phone and then after that first time it works untill the next restart. Now i have a rooted phone and idk if it changed, i reverted back to a pattern as that does not brings up issues, and i dont have means to check untill quarantine is over.

**Comment by SebiderSushi** [comment]
Huh, looks like you've got file based encryption and openboard is tripping over that - even though reading the source code it looks like openboard should be able to handle this kind of situation.
Maybe logs could be useful in this case.

[More on the topic](https://source.android.com/security/encryption/file-based.html)

**Comment by MSBack** [comment]
I am having the same issue.

**Comment by NauDev306** [comment]
Hi everyone,

Having the same issue on a Nokia 2.3 with Android 10. It used to work perfectly fine, but after the Google 2020-08-05 V1.2 update on 8/10/2020...after long search I just connected the physical keyboard as stated above

**Comment by dslul** [comment]
@justaguydoinghisstuff actually I get the same problem with gboard on Android 9, only the system keyboard is available at startup.

**Comment by Pentaphon** [comment]
> only the system keyboard is available at startup.

I think that's pretty much everybody's issue because OEMs don't want you to somehow disable the keyboard they want you to use.

**Comment by justaguydoinghisstuff** [comment]
I found a fix for it.
If you make OpenBoard as a system app then it will work propperly and start at boot. Os a workaround that i found and has been working for me.
I dont know why as i am simply an user not a dev. but it might work for all of you. 
I am rooted so it was pretty easy, idk if you can make an app a system app trough ADB.

**Comment by Netscaping** [comment]
I found this issue in the simple keyboard github. https://github.com/rkkr/simple-keyboard/issues/85
According to https://github.com/rkkr/simple-keyboard/issues/85#issuecomment-570791806. the keyboard has to support Direct Boot Mode in order to start at boot.
