### ISSUE TITLE
Accessibility: The button to go to the previous level does not work properly

### ISSUE THREAD

**Issue by bmivzkrp** [dslul/openboard#758]
Steps to reproduce:
0. Install a screen reader (TalkBack or Jieshuo) on your device. Then - turn on the TalkBack or Jieshuo service in the accessibility settings;
1. open Open Board settings;
2. Go to any settings section;
3. Double-tap the button in the upper left corner of the screen to go back one level.
Actual result: nothing happens.
Expected result: after activating this button, the focus should be at the previous level.
Note: By default, screen readers are configured to activate an element with a double tap. This is convenient for most blind users.
Open Board version: 1.4.5
Device: Impression ImSmart-C551 (Android 6.0).
I would be very grateful for your attention to this request.

**Comment by RHJihan** [comment]
I found this problem on the older versions of android. Works fine on Android 11+ as my test. Not sure about 9 or 10. You can use the system back button as a workaround.
Duplicate: #156
