### ISSUE TITLE
Full instructions for building .apk-file with additional dictionaries

### ISSUE THREAD

**Issue by Niklas81** [dslul/openboard#76]
Total newbie Android end user here (but developer on Arch linux), former iOS user, trying to get OpenBoard to work with a Swedish dictionary.

Could someone please provide clear instructions for people like me on how to get OpenBoard to work; how to create the file yourself and not just install it from F-droid? I know there's a long discussion going on, #31, regarding wheater more languages should included by default, or be downloadable as separate packages etc. But this might take a while to decide on, so for now I would be a very happy camper if you could simply provide an instruction that is simple to understand and that works. :smile:

The little I understand so far is that `.apk`-files are essentially renamed `.zip`-files. So what I've tried so far are these steps:
1. Cloned this repo.
2. Downloaded `sv_wordlist.combined.gz`, extracted `sv_wordlist.combined` and run it through `dicttool_aosp.jar`, with the command `java -jar dicttool_aosp.jar makedict -s sv_wordlist.combined -d main_sv.dict`, resulting in `main_sv.dict`.
3. Copied `main_sv.dict` to `openboard/app/src/main/res/raw/` of the cloned repo.
4. Navigated to `openboard/app/src/main`, in Dolphin file browser, selected all files and folders, right clicked and selected `Compress`->`Here (as zip)`
5. Changed permissions on created file, so all users may open/edit it, and made it executable.
6. Renamed it to `OpenBoard.apk`.
7. Synced it to my Android device using `Syncthing`.
8. Opened it in `File Manager` so it started installing.

Step 8 resulted in an error, that I think translates to `There was an error parsing the package`.

That's it. That's all I've tried, folks. Some help would be much appreciated!

**Comment by creativetrendsapps** [comment]
Do you get a specific build error?

**Comment by Niklas81** [comment]
You mean when I run `java -jar dicttool_aosp.jar makedict -s sv_wordlist.combined -d main_sv.dict`? Or is there some build step that I've missed?

**Comment by dslul** [comment]
@Niklas81 it gives you an error because the signature check fails if you modify the package. You can re-sign it with your signature (you could also install android studio, download from the manager sdk and ndk and compile the project).
