### ISSUE TITLE
Interaction is unresponsive desktop mode and unable to quit desktop mode

### ISSUE THREAD

**Issue by Inc0n** [dslul/openboard#788]
**Describe the bug**

After entering desktop mode.
The left bar with 10 buttons are labelled from A-J in the Tutorial PDF Section: The mode "Desktop", where button A or the first button would return the user to current page. However, instead it does nothing. None of the button respond.

**To Reproduce**
1. Open "openboard"
2. Click on "Show desktop"
3. Click on any of the buttons on the left vertical bar (its on the very left edge of the screen for me)
4. Nothing happens

**Expected behavior**

If the first button was clicked, I will be returned to the current page.

**Screenshots**

**Machine (please complete the following information):**
 - Device: Lenovo x13
 - OS: Ubuntu 22.04.2 LTS

**Additional context**
When I first experienced in issue, my cursor was turned into an eraser. This meant that I could not use my cursor to interact with any other applications. I had to open a terminal to kill log off.

The right bar, which shows a library of misc icons, are sometimes responsive.

**Comment by Ammako** [comment]
https://github.com/OpenBoard-org/OpenBoard/issues?

**Comment by Inc0n** [comment]
Oh, this is awkward 😅

**Comment by Inc0n** [comment]
> https://github.com/OpenBoard-org/OpenBoard/issues?

That is where this should be. Thanks 😆
