### ISSUE TITLE
Allow changing keyboard height 

### ISSUE THREAD

**Issue by jeroen7s** [dslul/openboard#8]
Allow setting custom height for keyboard, to save screen space while typing.

**Comment by dslul** [comment]
Implemented in commit 85b5b3c309485a06553fa9f0c991b3a692107f52.

<img src="https://user-images.githubusercontent.com/6121202/72391215-d9c6e200-372c-11ea-87fc-abaa554b49ff.jpg" width="300">

**Comment by jeroen7s** [comment]
That was quick.
Thanks a lot :)
