### ISSUE TITLE
Feature Request: Autotext

### ISSUE THREAD

**Issue by cityofsmiles** [dslul/openboard#81]
Hi. First I want to thank the developer for making an open-source keyboard app. I just want to request a feature that I always use in Multiling Keyboard. The Autotext feature lets me define shortcuts which the app automatically expand when I type them. For example, when I type "gm" and hit spacebar, it is automatically expanded as "good morning." This saves me a lot of time especially when I am coding/scripting/LaTeXing using my phone. I think this will also help the users of OpenBoard if this is implemented. Thank you so much dev.

**Comment by sandsturm** [comment]
But openboard has this feature already: OpenBoard Settings ⇨ Text Correction ⇨ Personal dictionary ⇨ (Select the dictionary)

Isn't this what your are looking for?

![gnome-shell-screenshot-0NKTJ0](https://user-images.githubusercontent.com/2701346/80682454-d3cdf480-8ac2-11ea-9650-6c21475b4045.png)

![gnome-shell-screenshot-A10MJ0](https://user-images.githubusercontent.com/2701346/80682459-d6304e80-8ac2-11ea-958d-e64c2191f0d6.png)

**Comment by cityofsmiles** [comment]
Yes! Thank you. I thought it's just a dictionary so I didn't use it.

**Comment by sandsturm** [comment]
Wonderful. Hope this helps you and you can use the feature.
