### ISSUE TITLE
Will this program ever be supported on the Universal Windows Platform (UWP)?

### ISSUE THREAD

**Issue by SecularSteve** [dslul/openboard#812]
**Is your feature request related to a problem? Please describe.**
We have a "Microsoft Surface Hub" Workstation at our workplace, and having a feasible open licence-free alternative to the packaged Microsoft Whiteboard seems like a good trade off.

The problem is that Surface Hub devices only support UWP apps, not MSIX. Something about safety and stability. Even the Developer mode doesn't let me install it.

**Describe the solution you'd like**
A UWP edition/installation package of OpenBoard compatible with Surface Hub Workspaces/devices.

**Describe alternatives you've considered**
Stick to Microsoft Whiteboard. I mean, it's more barebones, but it's the only way we can use a whiteboard on this device.

**Additional context**
Tried installing it once, didn't work no matter what I did.
If this is something that can't simply be resolved, I'll take it with a grain of salt, and move on.

**Comment by ItsHarper** [comment]
This is a different Openboard.

**Comment by SecularSteve** [comment]
How embarassing
