### ISSUE TITLE
Status of app development

### ISSUE THREAD

**Issue by kojid0** [dslul/openboard#82]
Is the app still being developed? Last release was more than 2 months ago... Really love the app but some bugs are so significant to me that I need to look for alternatives if this project is dead.

**Comment by Pentaphon** [comment]
I think it is. This isn't a huge project since most of it comes from updating to the latest AOSP Keyboard code so I don't expect heavy development except for a few new features, bugfixes, and privacy tweaks.

**Comment by fabianski7** [comment]
ping @dslul

**Comment by dslul** [comment]
Sorry, because of the lockdown here in Italy I don't have access to my pc right now. I hope development on this can start again as soon as possible.

**Comment by Glitchy-Tozier** [comment]
Looking forward to development starting again!

**Comment by kojid0** [comment]
I'm closing this now. The app had very much potential.
