### ISSUE TITLE
Feature request: Adjustable keyboard height

### ISSUE THREAD

**Issue by veluisg** [dslul/openboard#85]
Openboard is cool, but it could be great if we could be able to resize the height of keyboard. AOSP keyboard takes half screen no matter how big screen is. Simple-Screen has that feature, so it is possible.

**Comment by GLLM** [comment]
HI !
Just curious, how is is difference from the ability to resize openboard ? (you can select the %age of original size)
Thanks

**Comment by dslul** [comment]
It's already possible in the settings!
