### ISSUE TITLE
pt_PT spelcheck not working

### ISSUE THREAD

**Issue by joaojotta** [dslul/openboard#87]
I was twisting my head thinking this was a keyboard issue and that pt_PT just wasn't available when I picked the source codes abs actually saw the pt_PT and pt_BR were both actually there. Tried the BR and it worked but jot the PT.
What may be causing this to happen?

Thanks

BTW: the en_UK is working fine as well.

**Comment by sandsturm** [comment]
What exactly is not working? How can I reproduce?

**Comment by joaojotta** [comment]
I believe you can.
When you use most languages words are suggested as you type.
This happens in English, Portuguese (Brazil) and should also happen to Portuguese (Portugal) but it doesn't.
I can only assume it can't reach the word list file for some reason.


Here words are suggested according with the word list file:
![Screenshot_2020-04-28-10-16-45-581_it niedermann owncloud notes](https://user-images.githubusercontent.com/11931285/80470740-524b5a80-893a-11ea-8839-60955555acdc.jpg)


Here words are also suggested correctly:
![Screenshot_2020-04-28-10-17-23-183_it niedermann owncloud notes](https://user-images.githubusercontent.com/11931285/80470988-abb38980-893a-11ea-8e02-e78c0debe51b.jpg)


Here the keyboard is just guessing:
![Screenshot_2020-04-28-10-17-42-299_it niedermann owncloud notes](https://user-images.githubusercontent.com/11931285/80470867-7c9d1800-893a-11ea-9b3c-ae96044b1636.jpg)

**Comment by sandsturm** [comment]
Thank you very much. I think it is because there is a pt_BR but no pt or pt_PT dictionary. I will add it in my local environment and check if it works. 

Here you see the list of dictionaries for openboard: https://github.com/dslul/openboard/tree/master/app/src/main/res/raw

**Comment by joaojotta** [comment]
That's odd as there is one in the source files.
Wonder if a way to import such files could be a useful feature.
Thanks!

**Comment by joaojotta** [comment]
What is the pt_PT_wordlist.combined.gz file for?
How could I create pt_PT dictionary from the pt_BR one?

**Comment by sandsturm** [comment]
The data in https://github.com/dslul/openboard/tree/master/dictionaries is used to generate the binary version of the dictionaries, which you can find in https://github.com/dslul/openboard/tree/master/app/src/main/res/raw
