### ISSUE TITLE
Suggestion: Add Esperanto dictionary

### ISSUE THREAD

**Issue by roshavagarga** [dslul/openboard#88]
A wordlist and dictionary are available here:
https://android-review.googlesource.com/c/platform/packages/inputmethods/LatinIME/+/148322

**Comment by sandsturm** [comment]
I am happy to add this. But how is Esperanto identified on Android? The plain installation does not support Esperanto.

**Comment by roshavagarga** [comment]
Might this be connected? https://android-review.googlesource.com/c/platform/packages/inputmethods/LatinIME/+/30970

**Comment by roshavagarga** [comment]
Also, if there's a more straightforward way of creating dict files on Windows as a basic user, I'd appreciate any tutorials you might have, as I can contribute to at least one dictionary :)

**Comment by sandsturm** [comment]
I have a Samsung S10 and the Android Studio emulator has a plain Google Android source. I cannot find Esperanto as an input language. Do you have it on your mobile device?

**Comment by sandsturm** [comment]
I created pull request #92. You can add dictionaries by yourself by following this guidelines. But make sure you test the wordlist in the Android Studio emulator: https://github.com/dslul/openboard#contribute

**Comment by roshavagarga** [comment]
Thank you for the pull request. I've already seen those guidelines and they're not user-friendly enough for a non-dev like me. There's enough access for me to appropriately amass a balanced word count that could theoretically improve the Bulgarian dictionary (book sources - modern and classics, news articles, etc.) but no simple way. I'm guessing this is the only option currently available?

**Comment by sandsturm** [comment]
What you could do: add the missing words in the language file. The structure is straight forward, example: 
`word=unue,f=180,flags=,originalFreq=180`

Then attach it to the issue and I can generate the dictionary. No problem :-)

**Comment by roshavagarga** [comment]
That much I can do, but the issues I've noticed in the raw file are a bit bigger:
1. The overall frequency seems way off.
2. originalfreq as well as medical and other tags are missing entirely.
3. The dictionary can't handle adjectives in the proper manner. I'll skip the boring linguistics and just explain it as so:
Good = добър (male gender)
Better = по-добър
The best = най-добрия

The по and най prefixes with hyphenation can't be properly linked and I have no idea how that would be fixed. And the worse part is that there are a few exceptions where those should be used without hyphenation, but neither case is covered. On top of all of that, a lot of words are missing in general, which is probably the easiest fix.

How would I go about recalculating the frequency in some manner?

**Comment by sandsturm** [comment]
On the [aosp dictionary](https://github.com/remi0s/aosp-dictionary-tools) page they are using [translated texts](http://opus.nlpl.eu/index.php) or [subtitles](http://opus.nlpl.eu/OpenSubtitles2018.php) as an input.

**Comment by roshavagarga** [comment]
As far as input goes I was thinking of using translated and original novels from this [freely available massive library](https://chitanka.info/) as well as articles from news websites, official legal documents such as the State Newspaper and others. There's a multitude of resources freely available to gauge frequency, it's just the act of following the required steps after having amassed a large amount of texts that eludes me :/

**Comment by roshavagarga** [comment]
Dictionary added, closing.
