### ISSUE TITLE
Dictionnaries

### ISSUE THREAD

**Issue by kotecky** [dslul/openboard#91]
Does anything prevent the project to reuse the dictionaries used by other projects? E.g. https://github.com/LineageOS/android_packages_inputmethods_LatinIME/tree/lineage-17.1/dictionaries

**Comment by sandsturm** [comment]
I don't think so. The structure is the same. It is just a matter to generate/add the dictionaries to the repository. Do we want to add them to openboard source code, should I do it?

**Comment by roshavagarga** [comment]
The LineageOS dictionaries are more or less AOSP ones with some improvements here and there. As long as you keep the original authors I'd say it's productive to have them as long as they are superior to the ones we have, wherever there's an overlap. I would suggest some reciprocity by also opening merges of openboard dictionaries to LOS through https://review.lineageos.org

**Comment by sandsturm** [comment]
But even LineageOS sources it from Google. For example, [see here](https://review.lineageos.org/c/LineageOS/android_vendor_lineage/+/273198): Sourced from: https://android-review.googlesource.com/c/platform/packages/inputmethods/LatinIME/+/148322

https://android-review.googlesource.com/c/platform/packages/inputmethods/LatinIME/+/148322

**Comment by roshavagarga** [comment]
Definitely, but I believe a few of the other dict patches are modifications on top of that. The abandoned merges you linked are actually mine - I gave up on figuring out git just to upload 2 files to gerrit.

**Comment by kotecky** [comment]
@sandsturm 
> But even LineageOS sources it from Google.

I wrote the initial comment from a user's perspective. As such i would not mind using a dictionary sourced from Google provided it contains no tracking binaries or similar.

**Comment by sandsturm** [comment]
But did they ever update the dictionaries? The sources from Google and LineageOS are quite old, the last commit is 3 or 4 years old. Should we take them as the basis and add our own list of words in another file or fork them in the openboard repositories? In #83 I extended the original dictionary with words I missed and added them back to the repository. 

@dslul, what your opinion here?

**Comment by roshavagarga** [comment]
LineageOS uses the AOSP dictionaries as bases - some are improved, others aren't, without checking their gerrit there's no way to know what's been improved and what hasn't. I'm not sure whether openboard uses these as its basis, but if it does, any improvements to those can be forked over to LOS too and vice versa. In cases where they differ, there's no way to know which one is better without a user's input.

**Comment by sandsturm** [comment]
I have now added the de dictionary change to the Android sources: https://android-review.googlesource.com/c/platform/packages/inputmethods/LatinIME/+/1298694

My favorite solution would  be to use the Android repositories as the golden source.

**Comment by roshavagarga** [comment]
Cool. I suggest also sending that in the LineageOS gerrit, as AOSP rarely if ever accepts any changes to its AOSP keyboard, since they have entirely transitioned to the proprietary GBoard.

**Comment by sandsturm** [comment]
With pleasure. Should I wait until the change is approved by Google, or should I already make the change in LineageOS?

**Comment by roshavagarga** [comment]
Definitely don't wait. I'd wager your change will never get a response, let alone approval by Google. Just make sure authorship and whatnot is preserved.

**Comment by sandsturm** [comment]
Okay => https://github.com/LineageOS/android_packages_inputmethods_LatinIME/pull/2

**Comment by roshavagarga** [comment]
Changes are only reviewed and merged through their gerrit, available at https://review.lineageos.org/.

**Comment by sandsturm** [comment]
Tried to get around gerrit, but ok. https://review.lineageos.org/c/LineageOS/android_packages_inputmethods_LatinIME/+/274373

**Comment by roshavagarga** [comment]
@sandsturm Check the link, 2 comments you need to address and it'll be on the fast track for merging :)

**Comment by malekairmaroc7** [comment]
You can maybe add dictionary update server?

**Comment by sandsturm** [comment]
Is your question, when a new version is published which includes the dictionary?

**Comment by malekairmaroc7** [comment]
Is your question related to me @sandsturm ?

**Comment by sandsturm** [comment]
Yes :-)

**Comment by malekairmaroc7** [comment]
Oh then, yes that's what I mean 😁

**Comment by sandsturm** [comment]
Ah, yes. @dslul needs to do this ;-)

**Comment by malekairmaroc7** [comment]
yeah sure. @dslul 🤓😝😁

**Comment by dslul** [comment]
> Is your question, when a new version is published which includes the dictionary?

Before the end of this month!
