### ISSUE TITLE
caps lock

### ISSUE THREAD

**Issue by kotecky** [dslul/openboard#96]
Implement caps lock. This would be a quick win for a ... an occasional use. 

One possible way: tap on shift > shift, long press on shift > caps lock, tap again > back to normal case.

**Comment by kotecky** [comment]
Oh, after re-testing I found it is there. I did not discover it before, possibly because the delay seems longer than expected from the setting. Also, a visual feedback on the key icon would be suitable.

**Comment by Pentaphon** [comment]
> Also, a visual feedback on the key icon would be suitable.

I want this too.

**Comment by sandsturm** [comment]
But there is visual feedback. Here is a screenshot from the Android emulator.

Shift & Caps Locked
![image](https://user-images.githubusercontent.com/2701346/81656164-1682bb80-9437-11ea-91be-2fcceadecc4e.png)  ![image](https://user-images.githubusercontent.com/2701346/81656052-ffdc6480-9436-11ea-99e6-1dde9073af8b.png)

**Comment by kotecky** [comment]
Not with my installation (on 1.3 on Sony, Android 8), see screenshot attached: 

![Screenshot_20200512-104321](https://user-images.githubusercontent.com/2297444/81662417-d115bc80-943d-11ea-99c1-7a97e2429950.png)

**Comment by sandsturm** [comment]
Can you post a screenshot when you just activated shift? Isn't it just grey instead of white?
![image](https://user-images.githubusercontent.com/2701346/81666199-045a4a80-9442-11ea-990c-941cd184b2d9.png)  ![image](https://user-images.githubusercontent.com/2701346/81666235-0fad7600-9442-11ea-9d7a-5e80e09156db.png)

**Comment by kotecky** [comment]
Yes, that's the representation i get. Did not remark it happening -- it happens under one's finger so it's pretty secret ;) Maybe a "popup" (similarly as for the accented letters)? This case is an exception where I would tolerate a vibration (which is otherwise always off). 

Another option (or "additionally"?): the shift (or one-time caps-lock) stays grey after being pressed. As it is an obvious reaction of that key, it should not even blink (grey-white-grey, the "white" period corresponds to the time being pressed). Instead, it should turn white in the moment when the caps-lock becomes active.

**Comment by Pentaphon** [comment]
> Not with my installation (on 1.3 on Sony, Android 8), see screenshot attached:

I get exactly what you get.

**Comment by sandsturm** [comment]
Okay, I just checked with Android 8. It is the same behavior. I am sorry 🙈 but for me it the different modes are pretty obvious:

1. Default (grey background, grey arrow)
![image](https://user-images.githubusercontent.com/2701346/81797934-ae53d880-950f-11ea-9f55-161d51c7464e.png)

2. Shift (grey background, green arrow)
![image](https://user-images.githubusercontent.com/2701346/81797994-c6c3f300-950f-11ea-96e9-5163a5f2a917.png)

3. Caps lock (white background, green arrow)
![image](https://user-images.githubusercontent.com/2701346/81798091-e78c4880-950f-11ea-9918-54fe6908441c.png)

**Comment by Pentaphon** [comment]
> Okay, I just checked with Android 8. It is the same behavior. I am sorry 🙈 but for me it the different modes are pretty obvious:

Yeah I want the stick under the arrow for caps lock.

**Comment by dslul** [comment]
I'll consider this in the future with the themes revamp, for now I'll close as it's not really an issue.
