### ISSUE TITLE
Prefs option: add a space after an inserted word

### ISSUE THREAD

**Issue by kotecky** [dslul/openboard#97]
After a predicted word is tapped on, in general a space follows. Such a space should be added automatically, if the user opts in in the prefs.

**Comment by TheCrowned** [comment]
Yes! This would be so useful!

**Comment by TheCrowned** [comment]
I would even be willing to submit a pull request given some hints at where to start :)

**Comment by TheCrowned** [comment]
On revising this, it looks like this is already default behavior. In fact, the space is not visible after the word is tapped, but gets added if more writing is done. @kotecky if you confirm, I guess we can close this :)

**Comment by dslul** [comment]
Yes, it already adds a space if you write, but if you need to delete, it doesn't. So I think this issue can be closed :+1:

**Comment by jwsp1** [comment]
The space is only added after you start to write again, so the space is invisible which is bad for UX. I think that the user should see the added space right after he hits a word suggestion.
